"""
pgappforge/plugins/erp/hcm/variable_pay/__init__.py

VariablePayPlugin — HCM Variable Pay / Incentive Compensation ERP plugin.

Covers the full incentive lifecycle:
  IncentivePlan (tiers + accelerator) → EmployeeQuota → CommissionCalculation → CommissionPayout

Domain: hcm
Depends on: foundation

Events emitted:
  hcm.variable_pay.quota.assigned
  hcm.variable_pay.attainment.recorded
  hcm.variable_pay.commission.calculated
  hcm.variable_pay.commission.approved
  hcm.variable_pay.commission.paid
  hcm.variable_pay.accelerator.applied

Events consumed:
  hcm.payroll.run.calculated  (optionally marks commissions as paid)

Usage
-----
Add to your app config::

    PGAPPFORGE_PLUGINS = [
        "pgappforge.plugins.erp.foundation",
        "pgappforge.plugins.erp.hcm.variable_pay",
    ]

Or instantiate directly::

    from pgappforge.plugins.erp.hcm.variable_pay import VariablePayPlugin
    plugin = VariablePayPlugin(appbuilder)
    plugin.activate()
"""
from __future__ import annotations

import logging
from typing import Any

from pgappforge.plugins.base_plugin import BasePlugin, PluginMetadata, PluginPriority

log = logging.getLogger(__name__)


class VariablePayPlugin(BasePlugin):
	"""HCM Variable Pay ERP plugin.

	Registers plan, quota, calculation, and payout management views.
	Pre-configures Rules Engine rulesets for quota and payout state machines.
	"""

	name = "variable_pay"
	domain = "hcm"
	depends_on: list[str] = ["foundation"]

	# ------------------------------------------------------------------
	# Metadata
	# ------------------------------------------------------------------

	@property
	def metadata(self) -> PluginMetadata:
		return PluginMetadata(
			name="variable_pay",
			version="1.0.0",
			description=(
				"HCM Variable Pay — tiered incentive/commission plans with "
				"accelerators, quota tracking, attainment recording, tier-by-tier "
				"commission calculation, and payout lifecycle (PENDING → APPROVED → PAID)."
			),
			author="PgAppForge Contributors",
			tags=["hcm", "compensation", "commission", "incentives", "sales"],
			priority=PluginPriority.NORMAL,
			permissions=[
				"can_variable_pay_plan_list",
				"can_variable_pay_plan_write",
				"can_variable_pay_quota_list",
				"can_variable_pay_quota_write",
				"can_variable_pay_attainment_record",
				"can_variable_pay_commission_calculate",
				"can_variable_pay_payout_list",
				"can_variable_pay_payout_approve",
				"can_variable_pay_payout_pay",
				"can_variable_pay_analytics",
			],
			safe_mode_compatible=True,
		)

	# ------------------------------------------------------------------
	# get_events / subscribe_to
	# ------------------------------------------------------------------

	def get_events(self) -> list[str]:
		return [
			"hcm.variable_pay.quota.assigned",
			"hcm.variable_pay.attainment.recorded",
			"hcm.variable_pay.commission.calculated",
			"hcm.variable_pay.commission.approved",
			"hcm.variable_pay.commission.paid",
			"hcm.variable_pay.accelerator.applied",
		]

	def subscribe_to(self) -> list[str]:
		return [
			"hcm.payroll.run.calculated",
		]

	# ------------------------------------------------------------------
	# Lifecycle
	# ------------------------------------------------------------------

	def initialize(self) -> None:
		defaults: dict[str, Any] = {
			"VARIABLE_PAY_MENU_CATEGORY": "Variable Pay",
			"VARIABLE_PAY_DEFAULT_CURRENCY": "USD",
		}
		self.config = {**defaults, **self.config}
		log.info("VariablePayPlugin initialised (config keys: %s)", list(self.config))

	def register_views(self) -> None:
		# Views are registered lazily to keep import cost low.
		# Full view classes live in views.py (generated by the framework).
		log.info(
			"VariablePayPlugin: views registered under category %r",
			self.config.get("VARIABLE_PAY_MENU_CATEGORY", "Variable Pay"),
		)

	def register_models(self) -> list:
		from pgappforge.plugins.erp.hcm.variable_pay.models import (
			CommissionCalculation,
			CommissionPayout,
			EmployeeQuota,
			IncentivePlan,
		)
		return [IncentivePlan, EmployeeQuota, CommissionCalculation, CommissionPayout]

	# ------------------------------------------------------------------
	# Rules Engine pre-configuration
	# ------------------------------------------------------------------

	@staticmethod
	def setup_rules(session: Any) -> None:
		"""Pre-configure Rules Engine rulesets for variable pay domain.

		Idempotent — skips rulesets that already exist.
		"""
		try:
			from pgappforge.plugins.rules.models import Rule, RuleSet
		except ImportError:
			log.debug("VariablePayPlugin.setup_rules: rules plugin not available, skipping")
			return

		import sqlalchemy as sa

		RULESETS = [
			{
				"name": "variable_pay.quota.positive_quota_cents",
				"description": "Quota cents must be positive on creation",
				"model_name": "EmployeeQuota",
				"stop_on_match": True,
				"rules": [
					{
						"name": "require_positive_quota_cents",
						"trigger_event": "on_before_create",
						"conditions_json": [
							{"field": "quota_cents", "op": "lte", "value": 0},
						],
						"actions_json": [
							{"type": "raise_error",
							 "message": "quota_cents must be positive"}
						],
					},
				],
			},
			{
				"name": "variable_pay.quota.no_attainment_on_closed",
				"description": "Cannot record attainment on a CLOSED or CANCELLED quota",
				"model_name": "EmployeeQuota",
				"stop_on_match": True,
				"rules": [
					{
						"name": "block_attainment_closed_quota",
						"trigger_event": "on_before_update",
						"conditions_json": [
							{"field": "_action", "op": "eq", "value": "record_attainment"},
							{"field": "status", "op": "in", "value": ["CLOSED", "CANCELLED"]},
						],
						"actions_json": [
							{"type": "raise_error",
							 "message": "Cannot record attainment on a CLOSED or CANCELLED quota"}
						],
					},
				],
			},
			{
				"name": "variable_pay.payout.pending_only_approve",
				"description": "Only PENDING payouts can be approved",
				"model_name": "CommissionPayout",
				"stop_on_match": True,
				"rules": [
					{
						"name": "block_non_pending_approval",
						"trigger_event": "on_before_update",
						"conditions_json": [
							{"field": "_new_status", "op": "eq", "value": "APPROVED"},
							{"field": "_old_status", "op": "neq", "value": "PENDING"},
						],
						"actions_json": [
							{"type": "raise_error",
							 "message": "CommissionPayout must be in PENDING status to approve"}
						],
					},
				],
			},
			{
				"name": "variable_pay.payout.approved_only_paid",
				"description": "Only APPROVED payouts can be marked PAID",
				"model_name": "CommissionPayout",
				"stop_on_match": True,
				"rules": [
					{
						"name": "block_non_approved_payment",
						"trigger_event": "on_before_update",
						"conditions_json": [
							{"field": "_new_status", "op": "eq", "value": "PAID"},
							{"field": "_old_status", "op": "neq", "value": "APPROVED"},
						],
						"actions_json": [
							{"type": "raise_error",
							 "message": "CommissionPayout must be APPROVED before marking PAID"}
						],
					},
				],
			},
			{
				"name": "variable_pay.plan.positive_accelerator_multiplier",
				"description": "Accelerator multiplier must be >= 1.0 when set",
				"model_name": "IncentivePlan",
				"stop_on_match": True,
				"rules": [
					{
						"name": "require_positive_accelerator_multiplier",
						"trigger_event": "on_before_create",
						"conditions_json": [
							{"field": "accelerator_multiplier", "op": "lt", "value": 1.0},
						],
						"actions_json": [
							{"type": "raise_error",
							 "message": "accelerator_multiplier must be >= 1.0"}
						],
					},
				],
			},
		]

		for rs_def in RULESETS:
			existing = session.execute(
				sa.select(RuleSet).where(RuleSet.name == rs_def["name"])
			).scalar_one_or_none()
			if existing is not None:
				continue
			rs = RuleSet(
				name=rs_def["name"],
				description=rs_def["description"],
				model_name=rs_def["model_name"],
				stop_on_match=rs_def.get("stop_on_match", False),
				enabled=True,
			)
			session.add(rs)
			session.flush()
			for r_def in rs_def.get("rules", []):
				session.add(Rule(
					ruleset_id=rs.id,
					name=r_def["name"],
					trigger_event=r_def["trigger_event"],
					conditions_json=r_def["conditions_json"],
					actions_json=r_def["actions_json"],
					enabled=True,
				))
		log.info("VariablePayPlugin.setup_rules: %d rulesets configured", len(RULESETS))


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def create_plugin(
	appbuilder: Any,
	config: dict[str, Any] | None = None,
) -> VariablePayPlugin:
	return VariablePayPlugin(appbuilder, config=config or {})


# ---------------------------------------------------------------------------
# Public re-exports
# ---------------------------------------------------------------------------

from pgappforge.plugins.erp.hcm.variable_pay.models import (  # noqa: E402
	CommissionCalculation,
	CommissionPayout,
	EmployeeQuota,
	IncentivePlan,
)
from pgappforge.plugins.erp.hcm.variable_pay.events import (  # noqa: E402
	AcceleratorAppliedEvent,
	AttainmentRecordedEvent,
	CommissionApprovedEvent,
	CommissionCalculatedEvent,
	CommissionPaidEvent,
	QuotaAssignedEvent,
)
from pgappforge.plugins.erp.hcm.variable_pay.services import (  # noqa: E402
	CommissionCalculationError,
	PayoutNotFoundError,
	QuotaNotFoundError,
	VariablePayError,
	VariablePayService,
	VariablePayStateError,
)

__all__ = [
	# plugin
	"VariablePayPlugin",
	"create_plugin",
	# models
	"IncentivePlan",
	"EmployeeQuota",
	"CommissionCalculation",
	"CommissionPayout",
	# events
	"QuotaAssignedEvent",
	"AttainmentRecordedEvent",
	"CommissionCalculatedEvent",
	"CommissionApprovedEvent",
	"CommissionPaidEvent",
	"AcceleratorAppliedEvent",
	# services
	"VariablePayService",
	"VariablePayError",
	"QuotaNotFoundError",
	"PayoutNotFoundError",
	"VariablePayStateError",
	"CommissionCalculationError",
]
