"""
pgappforge/plugins/erp/crm/customer_portal/models.py

SQLAlchemy 2.x models for Customer Self-Service Portal.

Table prefix: cpt_
  cpt_user     — one portal account per AR customer per tenant
  cpt_session  — active session tokens (hashed)
  cpt_payment  — payment initiations from the portal
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship, Mapped, mapped_column

from pgappforge.models.sqla import Model


class CustomerPortalUser(Model):
	"""Portal user account — one per AR customer per tenant.

	Passwords are stored as bcrypt hashes (or SHA-256 fallback when bcrypt
	is unavailable).  Account lockout triggers after 5 consecutive failures:
	locked_until is set to now + 30 min.
	"""
	__tablename__ = "cpt_user"
	__table_args__ = (
		sa.Index("ix_cpt_user_tenant_email", "tenant_id", "email"),
		sa.Index("ix_cpt_user_tenant_customer", "tenant_id", "customer_id"),
	)

	id: Mapped[str] = mapped_column(sa.String(36), primary_key=True)
	tenant_id: Mapped[str | None] = mapped_column(sa.String(50), nullable=True, index=True)

	customer_id: Mapped[str] = mapped_column(sa.String(50), nullable=False)
	email: Mapped[str] = mapped_column(sa.String(320), nullable=False)
	password_hash: Mapped[str] = mapped_column(sa.String(256), nullable=False)

	is_active: Mapped[bool] = mapped_column(sa.Boolean, nullable=False, default=True)
	last_login_at: Mapped[sa.DateTime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)
	failed_login_count: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=0)
	locked_until: Mapped[sa.DateTime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)

	sessions: Mapped[list[PortalSession]] = relationship(
		"PortalSession",
		back_populates="user",
		cascade="all, delete-orphan",
	)

	def __repr__(self) -> str:
		return f"<CustomerPortalUser customer={self.customer_id!r} email={self.email!r}>"


class PortalSession(Model):
	"""Active portal session.

	Raw token is generated by the service and returned to the caller once.
	Only the SHA-256 hash is persisted (session_token_hash).
	"""
	__tablename__ = "cpt_session"
	__table_args__ = (
		sa.Index("ix_cpt_session_token_hash", "session_token_hash", unique=True),
		sa.Index("ix_cpt_session_user_revoked", "user_id", "is_revoked"),
	)

	id: Mapped[str] = mapped_column(sa.String(36), primary_key=True)
	tenant_id: Mapped[str | None] = mapped_column(sa.String(50), nullable=True)

	user_id: Mapped[str] = mapped_column(
		sa.String(36),
		sa.ForeignKey("cpt_user.id", ondelete="CASCADE"),
		nullable=False,
	)
	session_token_hash: Mapped[str] = mapped_column(sa.String(64), nullable=False, unique=True)
	expires_at: Mapped[sa.DateTime] = mapped_column(sa.DateTime(timezone=True), nullable=False)
	ip_address: Mapped[str | None] = mapped_column(sa.String(45), nullable=True)
	is_revoked: Mapped[bool] = mapped_column(sa.Boolean, nullable=False, default=False)

	user: Mapped[CustomerPortalUser] = relationship("CustomerPortalUser", back_populates="sessions")

	def __repr__(self) -> str:
		return f"<PortalSession user={self.user_id!r} revoked={self.is_revoked}>"


class PortalPayment(Model):
	"""Payment initiated from the self-service portal.

	amount_cents — always stored as integer cents (BigInteger).
	invoice_ids  — JSONB list of AR invoice ID strings being paid.

	status lifecycle: PENDING → CONFIRMED | FAILED | REFUNDED
	"""
	__tablename__ = "cpt_payment"
	__table_args__ = (
		sa.Index("ix_cpt_payment_customer_status", "customer_id", "status"),
		sa.Index("ix_cpt_payment_tenant_status", "tenant_id", "status"),
	)

	id: Mapped[str] = mapped_column(sa.String(36), primary_key=True)
	tenant_id: Mapped[str | None] = mapped_column(sa.String(50), nullable=True, index=True)

	customer_id: Mapped[str] = mapped_column(sa.String(50), nullable=False)
	invoice_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
	amount_cents: Mapped[int] = mapped_column(sa.BigInteger, nullable=False)
	payment_method: Mapped[str] = mapped_column(sa.String(30), nullable=False)
	reference: Mapped[str | None] = mapped_column(sa.String(100), nullable=True)

	status: Mapped[str] = mapped_column(sa.String(20), nullable=False, default="PENDING")
	initiated_at: Mapped[sa.DateTime] = mapped_column(
		sa.DateTime(timezone=True),
		nullable=False,
		server_default=sa.func.now(),
	)
	confirmed_at: Mapped[sa.DateTime | None] = mapped_column(sa.DateTime(timezone=True), nullable=True)

	def __repr__(self) -> str:
		return f"<PortalPayment customer={self.customer_id!r} amount={self.amount_cents} status={self.status!r}>"


__all__ = [
	"CustomerPortalUser",
	"PortalSession",
	"PortalPayment",
]
