"""
Built-in ReportForge business report templates.

Each template describes how to pre-configure a new Report with
bands, fields, branding defaults, and sample SQL.

Available templates
-------------------
invoice          — Sales invoice with line items, tax, total
quote            — Customer quotation / price list
statement        — Statement of account (balance, transactions)
business_letter  — Formal business letter (mail merge from a query)
tabular          — Generic data table (simplest starting point)
summary          — Executive summary with totals/KPIs per group
"""

from __future__ import annotations
from typing import Any


def _band(band_type, height_mm, bg="#ffffff", fields=None):
    return {"band_type": band_type, "height_mm": height_mm,
            "background_color": bg, "fields": fields or []}


def _field(ftype, x, y, w, h, text="", binding="", fmt="",
           bold=False, size=10, align="left",
           color="#000000", bg="transparent"):
    style = {"font_size": size, "bold": bold, "align": align,
              "color": color, "bg_color": bg}
    if text:
        style["text"] = text
    return {"field_type": ftype, "x_mm": x, "y_mm": y,
            "width_mm": w, "height_mm": h,
            "data_binding": binding or None,
            "format_string": fmt or None, "style": style}


TEMPLATES = {

    "invoice": {
        "label": "Sales Invoice",
        "description": "Professional sales invoice with line items, subtotal, tax, and total.",
        "icon": "fa-file-invoice-dollar",
        "template_key": "invoice",
        "primary_color": "#1a3a5c",
        "secondary_color": "#4a86c8",
        "sample_sql": (
            "SELECT o.id AS invoice_number, o.created_at AS invoice_date,\n"
            "  c.name AS customer_name, c.address AS customer_address,\n"
            "  p.name AS item_description, oi.quantity AS qty,\n"
            "  oi.unit_price, oi.quantity * oi.unit_price AS line_total\n"
            "FROM orders o\n"
            "JOIN customers c ON c.id = o.customer_id\n"
            "JOIN order_items oi ON oi.order_id = o.id\n"
            "JOIN products p ON p.id = oi.product_id\n"
            "WHERE o.id = :invoice_number ORDER BY oi.id"
        ),
        "parameters": [
            {"name": "invoice_number", "type": "integer",
             "label": "Invoice Number", "default": "1", "required": True}
        ],
        "bands": [
            _band("title", 35, "#1a3a5c", [
                _field("text", 0, 2, 120, 8, text="INVOICE", bold=True, size=22, color="#ffffff"),
                _field("text", 0, 14, 120, 6, binding="customer_name", bold=True, size=11, color="#ffffff"),
                _field("text", 0, 21, 120, 5, binding="customer_address", size=9, color="#ccddee"),
                _field("text", 130, 2, 60, 5, text="Invoice No:", bold=True, size=9, align="right", color="#ffffff"),
                _field("text", 130, 8, 60, 5, binding="invoice_number", size=12, align="right", bold=True, color="#ffffff"),
                _field("text", 130, 15, 60, 5, text="Date:", size=9, align="right", color="#ccddee"),
                _field("date", 130, 21, 60, 5, binding="invoice_date", fmt="{:%d %b %Y}", size=9, align="right", color="#ffffff"),
            ]),
            _band("column_header", 8, "#e8eff7", [
                _field("text",  0, 1, 80, 6, text="Description", bold=True, size=9, color="#1a3a5c"),
                _field("text", 82, 1, 20, 6, text="Qty", bold=True, size=9, align="right", color="#1a3a5c"),
                _field("text",104, 1, 25, 6, text="Unit Price", bold=True, size=9, align="right", color="#1a3a5c"),
                _field("text",131, 1, 30, 6, text="Line Total", bold=True, size=9, align="right", color="#1a3a5c"),
            ]),
            _band("detail", 8, "#ffffff", [
                _field("text",  0, 1, 80, 6, binding="item_description", size=9),
                _field("number",82, 1, 20, 6, binding="qty", fmt="{:,}", size=9, align="right"),
                _field("number",104, 1, 25, 6, binding="unit_price", fmt="{:,.2f}", size=9, align="right"),
                _field("number",131, 1, 30, 6, binding="line_total", fmt="{:,.2f}", size=9, align="right"),
            ]),
            _band("summary", 20, "#f5f5f5", [
                _field("text", 104, 2, 25, 6, text="TOTAL DUE:", bold=True, size=11, align="right", color="#1a3a5c"),
                _field("number",131, 2, 30, 6, binding="line_total", fmt="{:,.2f}", bold=True, size=12, align="right", color="#1a3a5c"),
                _field("text", 0, 12, 160, 5, text="Thank you for your business.", size=9, color="#666666", align="center"),
            ]),
            _band("page_footer", 8, "#1a3a5c", [
                _field("text", 0, 2, 190, 5, text="Generated by ReportForge", size=8, color="#aaccee", align="center"),
            ]),
        ],
    },

    "quote": {
        "label": "Customer Quotation",
        "description": "Formal quote / proposal with validity date and acceptance terms.",
        "icon": "fa-file-contract",
        "template_key": "quote",
        "primary_color": "#2d6a2d",
        "secondary_color": "#5da85d",
        "sample_sql": (
            "SELECT q.id AS quote_number, q.created_at AS quote_date,\n"
            "  q.valid_until, c.name AS customer_name,\n"
            "  i.description AS item_description, i.quantity AS qty,\n"
            "  i.unit_price, i.quantity * i.unit_price AS line_total\n"
            "FROM quotes q\n"
            "JOIN customers c ON c.id = q.customer_id\n"
            "JOIN quote_items i ON i.quote_id = q.id\n"
            "WHERE q.id = :quote_number"
        ),
        "parameters": [
            {"name": "quote_number", "type": "integer", "label": "Quote Number", "default": "1", "required": True}
        ],
        "bands": [
            _band("title", 25, "#2d6a2d", [
                _field("text", 0, 3, 120, 8, text="QUOTATION", bold=True, size=20, color="#ffffff"),
                _field("text", 0, 14, 120, 5, binding="customer_name", bold=True, size=11, color="#ccffcc"),
                _field("text", 130, 3, 60, 5, binding="quote_number", bold=True, size=12, align="right", color="#ffffff"),
                _field("date", 130, 10, 60, 5, binding="valid_until", fmt="Valid until: {:%d %b %Y}", size=8, align="right", color="#ccffcc"),
            ]),
            _band("column_header", 8, "#e5f2e5", [
                _field("text",  0, 1, 80, 6, text="Item", bold=True, size=9, color="#2d6a2d"),
                _field("text", 82, 1, 20, 6, text="Qty", bold=True, size=9, align="right", color="#2d6a2d"),
                _field("text",104, 1, 25, 6, text="Unit Price", bold=True, size=9, align="right", color="#2d6a2d"),
                _field("text",131, 1, 30, 6, text="Total", bold=True, size=9, align="right", color="#2d6a2d"),
            ]),
            _band("detail", 8, "#ffffff", [
                _field("text",  0, 1, 80, 6, binding="item_description", size=9),
                _field("number",82, 1, 20, 6, binding="qty", fmt="{:,}", size=9, align="right"),
                _field("number",104, 1, 25, 6, binding="unit_price", fmt="{:,.2f}", size=9, align="right"),
                _field("number",131, 1, 30, 6, binding="line_total", fmt="{:,.2f}", size=9, align="right"),
            ]),
            _band("summary", 24, "#f0f7f0", [
                _field("text", 104, 2, 25, 6, text="TOTAL:", bold=True, size=11, align="right", color="#2d6a2d"),
                _field("number",131, 2, 30, 6, binding="line_total", fmt="{:,.2f}", bold=True, size=12, align="right", color="#2d6a2d"),
                _field("text", 0, 14, 190, 7, text="This quotation is valid for 30 days. Please confirm acceptance in writing.", size=8, color="#555555"),
            ]),
        ],
    },

    "statement": {
        "label": "Statement of Account",
        "description": "Periodic account statement with running balance.",
        "icon": "fa-file-alt",
        "template_key": "statement",
        "primary_color": "#4a2080",
        "secondary_color": "#8a60c0",
        "sample_sql": (
            "SELECT t.transaction_date AS txn_date, t.reference, t.description,\n"
            "  CASE WHEN t.amount > 0 THEN t.amount END AS debit,\n"
            "  CASE WHEN t.amount < 0 THEN ABS(t.amount) END AS credit,\n"
            "  SUM(t.amount) OVER (PARTITION BY t.account_id ORDER BY t.transaction_date ROWS UNBOUNDED PRECEDING) AS running_balance\n"
            "FROM transactions t\n"
            "WHERE t.account_id = :account_id\n"
            "  AND t.transaction_date BETWEEN :from_date AND :to_date\n"
            "ORDER BY t.transaction_date"
        ),
        "parameters": [
            {"name": "account_id", "type": "integer", "label": "Account ID", "required": True},
            {"name": "from_date", "type": "date", "label": "From Date", "default": "2024-01-01"},
            {"name": "to_date", "type": "date", "label": "To Date", "default": "2024-12-31"},
        ],
        "bands": [
            _band("title", 20, "#4a2080", [
                _field("text", 0, 3, 190, 8, text="STATEMENT OF ACCOUNT", bold=True, size=16, color="#ffffff"),
            ]),
            _band("column_header", 8, "#e8e0f4", [
                _field("text",  0, 1, 30, 6, text="Date", bold=True, size=9, color="#4a2080"),
                _field("text", 32, 1, 25, 6, text="Reference", bold=True, size=9, color="#4a2080"),
                _field("text", 59, 1, 70, 6, text="Description", bold=True, size=9, color="#4a2080"),
                _field("text",131, 1, 20, 6, text="Debit", bold=True, size=9, align="right", color="#4a2080"),
                _field("text",153, 1, 20, 6, text="Credit", bold=True, size=9, align="right", color="#4a2080"),
                _field("text",175, 1, 25, 6, text="Balance", bold=True, size=9, align="right", color="#4a2080"),
            ]),
            _band("detail", 7, "#ffffff", [
                _field("date",   0, 1, 30, 5, binding="txn_date", fmt="{:%d/%m/%Y}", size=8),
                _field("text",  32, 1, 25, 5, binding="reference", size=8),
                _field("text",  59, 1, 70, 5, binding="description", size=8),
                _field("number",131, 1, 20, 5, binding="debit", fmt="{:,.2f}", size=8, align="right", color="#cc2200"),
                _field("number",153, 1, 20, 5, binding="credit", fmt="{:,.2f}", size=8, align="right", color="#007722"),
                _field("number",175, 1, 25, 5, binding="running_balance", fmt="{:,.2f}", size=8, align="right", bold=True),
            ]),
        ],
    },

    "business_letter": {
        "label": "Business Letter",
        "description": "Formal mail-merge letter with recipient address and body text.",
        "icon": "fa-envelope-open-text",
        "template_key": "business_letter",
        "primary_color": "#1a1a1a",
        "secondary_color": "#555555",
        "sample_sql": (
            "SELECT c.name AS recipient_name, c.title AS recipient_title,\n"
            "  c.address_line1, c.city, c.country, CURRENT_DATE AS letter_date\n"
            "FROM contacts c WHERE c.id = :contact_id"
        ),
        "parameters": [
            {"name": "contact_id", "type": "integer", "label": "Contact ID", "required": True}
        ],
        "bands": [
            _band("title", 30, "#ffffff", [
                _field("text", 0, 0, 190, 8, text="[Company Name]", bold=True, size=14, color="#1a1a1a"),
                _field("text", 0, 9, 190, 5, text="[Address]  ·  [City]  ·  [Phone]", size=9, color="#555555"),
            ]),
            _band("page_header", 35, "#ffffff", [
                _field("date",  0, 2, 80, 5, binding="letter_date", fmt="{:%d %B %Y}", size=10),
                _field("text",  0, 10, 80, 5, binding="recipient_title", size=10),
                _field("text",  0, 16, 80, 5, binding="recipient_name", size=10, bold=True),
                _field("text",  0, 22, 80, 5, binding="address_line1", size=10),
                _field("text",  0, 28, 80, 5, binding="city", size=10),
            ]),
            _band("detail", 50, "#ffffff", [
                _field("text", 0, 2, 190, 5, text="Dear {recipient_title} {recipient_name},", size=10, bold=True),
                _field("text", 0, 10, 190, 35,
                       text="[Your letter body goes here. Use AI Augment to generate text.\n\nYours sincerely,]",
                       size=10),
                _field("text", 0, 48, 80, 5, text="[Signature Name]", size=10),
            ]),
        ],
    },

    "tabular": {
        "label": "Tabular Report",
        "description": "Clean data table — the simplest starting point for any query.",
        "icon": "fa-table",
        "template_key": "tabular",
        "primary_color": "#0066cc",
        "secondary_color": "#4499dd",
        "sample_sql": "SELECT * FROM your_table LIMIT 100",
        "parameters": [],
        "bands": [
            _band("title", 15, "#0066cc", [
                _field("text", 0, 3, 190, 8, text="Report Title", bold=True, size=16, color="#ffffff"),
            ]),
            _band("column_header", 8, "#e0eeff", []),
            _band("detail", 7, "#ffffff", []),
            _band("summary", 10, "#f8f8f8", [
                _field("text", 0, 2, 190, 5, text="End of report", size=8, color="#888888", align="center"),
            ]),
        ],
    },

    "summary": {
        "label": "Executive Summary",
        "description": "KPI / group totals with aggregate footer.",
        "icon": "fa-chart-bar",
        "template_key": "summary",
        "primary_color": "#b34700",
        "secondary_color": "#e88a44",
        "sample_sql": (
            "SELECT department, COUNT(*) AS headcount,\n"
            "  SUM(salary) AS total_salary, AVG(salary) AS avg_salary\n"
            "FROM employees GROUP BY department ORDER BY department"
        ),
        "parameters": [],
        "bands": [
            _band("title", 20, "#b34700", [
                _field("text", 0, 3, 190, 10, text="Executive Summary", bold=True, size=18, color="#ffffff"),
            ]),
            _band("column_header", 8, "#fde8d8", [
                _field("text",  0, 1, 50, 6, text="Department", bold=True, size=9, color="#b34700"),
                _field("text", 52, 1, 30, 6, text="Headcount", bold=True, size=9, align="right", color="#b34700"),
                _field("text", 84, 1, 40, 6, text="Total Salary", bold=True, size=9, align="right", color="#b34700"),
                _field("text",126, 1, 35, 6, text="Avg Salary", bold=True, size=9, align="right", color="#b34700"),
            ]),
            _band("detail", 8, "#ffffff", [
                _field("text",   0, 1, 50, 6, binding="department"),
                _field("number",52, 1, 30, 6, binding="headcount", fmt="{:,}", align="right"),
                _field("number",84, 1, 40, 6, binding="total_salary", fmt="{:,.0f}", align="right"),
                _field("number",126, 1, 35, 6, binding="avg_salary", fmt="{:,.0f}", align="right"),
            ]),
        ],
    },
}


def get_template(key):
    """Return the template dict for the given key, or None."""
    return TEMPLATES.get(key)


def list_templates():
    """Return list of template metadata dicts."""
    return [
        {"key": k, "label": t["label"], "description": t["description"], "icon": t.get("icon", "fa-file")}
        for k, t in TEMPLATES.items()
    ]
