"""
ReportForge email dispatch — sends a report as a PDF/DOCX/XLSX attachment.

Uses smtplib (stdlib) with optional Flask-Mail fallback.
SMTP settings are read from Flask app config:
    REPORTFORGE_SMTP_HOST     default "localhost"
    REPORTFORGE_SMTP_PORT     default 587
    REPORTFORGE_SMTP_USER     default ""
    REPORTFORGE_SMTP_PASSWORD default ""
    REPORTFORGE_SMTP_TLS      default True
    REPORTFORGE_FROM_EMAIL    default "reports@localhost"
    REPORTFORGE_FROM_NAME     default "ReportForge"
"""

from __future__ import annotations

import io
import logging
import re
import smtplib
import threading
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
	from sqlalchemy.orm import Session
	from .models import Report, ReportDispatch

log = logging.getLogger(__name__)

_MIME_TYPES = {
	"pdf":  ("application/pdf",                               ".pdf"),
	"docx": ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"),
	"xlsx": ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",      ".xlsx"),
	"csv":  ("text/csv",                                      ".csv"),
	"html": ("text/html",                                     ".html"),
}


def _smtp_config(app) -> dict[str, Any]:
	return {
		"host":     app.config.get("REPORTFORGE_SMTP_HOST",     "localhost"),
		"port":     int(app.config.get("REPORTFORGE_SMTP_PORT", 587)),
		"user":     app.config.get("REPORTFORGE_SMTP_USER",     ""),
		"password": app.config.get("REPORTFORGE_SMTP_PASSWORD", ""),
		"tls":      app.config.get("REPORTFORGE_SMTP_TLS",      True),
		"from":     app.config.get("REPORTFORGE_FROM_EMAIL",    "reports@localhost"),
		"name":     app.config.get("REPORTFORGE_FROM_NAME",     "ReportForge"),
	}


def send_report_email(
	dispatch: ReportDispatch,
	attachment_bytes: bytes,
	session: Session,
	app: Any,
) -> None:
	"""
	Send a ReportDispatch record by email, then update its status.

	Args:
	    dispatch: the ReportDispatch ORM row (report + email metadata).
	    attachment_bytes: the rendered report bytes (PDF, DOCX, etc.).
	    session: SQLAlchemy session for updating dispatch status.
	    app: Flask app instance for SMTP config.

	Raises:
	    Exception: on SMTP failure (status is set to "failed" in DB before raising).
	"""
	from .models import DispatchStatus

	report = dispatch.report
	fmt = dispatch.export_format or "pdf"
	mime_type, ext = _MIME_TYPES.get(fmt, ("application/octet-stream", ".bin"))
	cfg = _smtp_config(app)

	# ── Sanitize headers against injection (strip CR/LF) ─────────────────
	def _safe_header(value: str) -> str:
		"""Remove CR and LF from header values to prevent injection."""
		return re.sub(r"[\r\n]", " ", (value or "").strip())

	to_safe      = _safe_header(dispatch.to_email)
	subject_safe = _safe_header(dispatch.subject or f"Report: {report.name}")
	cc_safe      = _safe_header(dispatch.cc_email or "")

	# Validate recipient addresses minimally
	_email_re = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
	recipients_raw = [a.strip() for a in to_safe.split(",") if a.strip()]
	invalid = [a for a in recipients_raw if not _email_re.match(a)]
	if invalid:
		raise ValueError(f"Invalid email addresses: {invalid}")

	# Honour optional allowlist (REPORTFORGE_EMAIL_ALLOWLIST = ["@example.com"])
	allowlist = app.config.get("REPORTFORGE_EMAIL_ALLOWLIST", [])
	if allowlist:
		for addr in recipients_raw:
			if not any(addr.endswith(d) for d in allowlist):
				raise ValueError(
					f"Recipient {addr!r} not in REPORTFORGE_EMAIL_ALLOWLIST"
				)

	# ── Build message ────────────────────────────────────────────────────
	msg = MIMEMultipart("mixed")
	msg["From"]    = f"{cfg['name']} <{cfg['from']}>"
	msg["To"]      = to_safe
	msg["Subject"] = subject_safe
	if cc_safe:
		msg["Cc"] = cc_safe

	# Body
	body_text = dispatch.body_text or (
		f"Please find attached the report '{report.name}'.\n\n"
		f"Generated by ReportForge."
	)
	msg.attach(MIMEText(body_text, "plain", "utf-8"))

	# Attachment
	filename = f"{report.name.replace(' ', '_')}{ext}"
	part = MIMEApplication(attachment_bytes, Name=filename)
	part["Content-Disposition"] = f'attachment; filename="{filename}"'
	part.set_type(mime_type)
	msg.attach(part)

	# ── Send ─────────────────────────────────────────────────────────────
	recipients = recipients_raw  # already validated above
	if cc_safe:
		recipients = recipients + [a.strip() for a in cc_safe.split(",") if a.strip()]

	try:
		if cfg["tls"]:
			server = smtplib.SMTP(cfg["host"], cfg["port"], timeout=30)
			server.ehlo()
			server.starttls()
			server.ehlo()
		else:
			server = smtplib.SMTP(cfg["host"], cfg["port"], timeout=30)

		if cfg["user"] and cfg["password"]:
			server.login(cfg["user"], cfg["password"])

		server.sendmail(cfg["from"], recipients, msg.as_string())
		server.quit()

		dispatch.status = DispatchStatus.SENT
		dispatch.sent_at = datetime.now(timezone.utc)
		dispatch.error_message = None
		log.info("ReportForge: dispatched report %r to %s", report.name, dispatch.to_email)

	except Exception as exc:
		dispatch.status = DispatchStatus.FAILED
		dispatch.error_message = str(exc)
		log.exception("ReportForge: dispatch failed for report %r", report.name)
		session.commit()
		raise

	session.commit()


def dispatch_async(
	report,
	to_email: str,
	subject: str,
	body_text: str,
	export_format: str,
	params: dict,
	engine,
	session,
	app,
) -> None:
	"""
	Non-blocking dispatch — spawns a daemon thread so the HTTP response
	returns immediately. Falls back to Celery if ``REPORTFORGE_USE_CELERY``
	is configured (not implemented yet — extend here).

	NOTE: The session must not be used by the thread after the request ends.
	A new session is created inside the thread for that reason.
	"""
	from flask import copy_current_request_context

	@copy_current_request_context
	def _run():
		try:
			dispatch_now(
				report=report,
				to_email=to_email,
				subject=subject,
				body_text=body_text,
				export_format=export_format,
				params=params,
				engine=engine,
				session=session,
				app=app,
			)
		except Exception:
			log.exception("ReportForge async dispatch failed for report %r", getattr(report, "name", "?"))

	t = threading.Thread(target=_run, daemon=True)
	t.start()


def dispatch_now(
	report: Report,
	to_email: str,
	subject: str,
	body_text: str,
	export_format: str,
	params: dict[str, Any],
	engine,  # ReportEngine
	session: Session,
	app: Any,
) -> ReportDispatch:
	"""
	Convenience: render + send in one call. Creates and saves a dispatch record.

	Returns the ReportDispatch with status=sent or status=failed.
	"""
	from .models import ReportDispatch, DispatchStatus

	dispatch = ReportDispatch(
		report_id=report.id,
		to_email=to_email,
		subject=subject,
		body_text=body_text,
		export_format=export_format,
		params_json=params or {},
		status=DispatchStatus.PENDING,
	)
	session.add(dispatch)
	session.flush()  # get the id

	# Render using the public engine API
	try:
		if export_format == "docx":
			from .docx_export import generate_docx
			rows = engine.fetch_rows(report.id, params)
			attachment = generate_docx(report, rows)
		elif export_format == "xlsx":
			attachment = engine.generate_excel(report.id, params)
		elif export_format == "csv":
			attachment = engine.generate_csv(report.id, params).encode("utf-8")
		else:
			attachment = engine.generate_pdf(report.id, params)
	except Exception as exc:
		dispatch.status = DispatchStatus.FAILED
		dispatch.error_message = f"Render error: {exc}"
		session.commit()
		return dispatch

	send_report_email(dispatch, attachment, session, app)
	return dispatch
