"""Performance test generation.

Produces a Locust file and a pytest-benchmark file for each table so load tests
are generated from the same schema inspection as unit tests.
"""

from __future__ import annotations

from typing import Any, Dict

from .base_generator import BaseTestGenerator


def _table_names(schema: Any) -> list[str]:
    """Normalise whatever the schema inspector returns into table names."""
    tables = getattr(schema, "tables", schema)
    if isinstance(tables, dict):
        return [str(name) for name in tables]
    if isinstance(tables, (list, tuple, set)):
        return [str(getattr(t, "name", t)) for t in tables]
    return []


class PerformanceTestGenerator(BaseTestGenerator):
    """Generates load and benchmark tests for the inspected schema."""

    generator_name = "performance"

    def generate_all_tests(self, schema: Any) -> Dict[str, str]:
        tables = _table_names(schema)
        files: Dict[str, str] = {}
        if tables:
            files["locustfile.py"] = self._generate_locust_file(tables)
            files["tests/performance/test_benchmarks.py"] = self._generate_benchmark_file(tables)
        return files

    def _generate_locust_file(self, tables: list[str]) -> str:
        table = tables[0]
        return f'''"""Auto-generated by pgappforge.testing_framework. Do not edit by hand."""

from locust import HttpUser, between, task


class ApiUser(HttpUser):
    wait_time = between(0.1, 0.5)

    @task(3)
    def list_rows(self):
        self.client.get("/api/v1/{table}/", name="GET /api/v1/{table}/")

    @task(1)
    def read_one(self):
        self.client.get("/api/v1/{table}/1", name="GET /api/v1/{table}/<id>")
'''

    def _generate_benchmark_file(self, tables: list[str]) -> str:
        rows = "\n".join(
            f'''
def test_benchmark_{name}(benchmark):
    def _call():
        from pgappforge import db
        from {name} import {name}
        db.session.query({name}).count()

    benchmark(_call)
'''.strip()
            for name in tables[:10]
        )
        return '"""Auto-generated micro-benchmarks."""\n' + rows + "\n"
