"""
pgappforge/plugins/offline/__init__.py

Offline-first PWA plugin for PgAppForge.

Provides a Service Worker (sw.js), a Web App Manifest (manifest.json), a
server-side sync endpoint, and a vanilla-JS IndexedDB client helper that
queues mutations when offline and auto-syncs on reconnect.

How to enable
-------------
Add to your Flask config::

	PGAPPFORGE_OFFLINE_ENABLED = True
	PGAPPFORGE_PLUGINS = ["pgappforge.plugins.offline"]

Or instantiate directly::

	from pgappforge.plugins.offline import create_plugin
	plugin = create_plugin(appbuilder)
	plugin.activate()

Config keys
-----------
``PGAPPFORGE_OFFLINE_ENABLED`` : bool, default False
	Master switch. Plugin views and blueprint are registered regardless;
	this controls whether the SW and manifest are served and whether the
	sync endpoint is open.

``PGAPPFORGE_OFFLINE_CACHE_TTL`` : int (seconds), default 3600
	Max-age hint embedded in the SW cache strategy for API responses.

``PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY`` : "server_wins"|"client_wins"|"manual"
	Default conflict resolution strategy. Can be overridden per model via
	the ``conflict_strategies`` config key (dict[model_name, strategy]).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

from flask import Blueprint, Response, jsonify, make_response, request
from flask import render_template_string

from pgappforge import BaseView, expose
from pgappforge.security.decorators import has_access
from pgappforge.plugins.base_plugin import BasePlugin, PluginMetadata, PluginPriority

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Optional SQLAlchemy model guard
# ---------------------------------------------------------------------------

try:
	from sqlalchemy import (
		Column, DateTime, Index, Integer, String, Text,
	)
	from sqlalchemy.dialects.postgresql import JSONB
	from pgappforge import Model

	class SyncConflict(Model):
		"""
		Persisted record of a sync conflict between a client write and the
		server's current state.

		Resolution strategies
		---------------------
		``server_wins``
			Server data is canonical; client change is discarded.
		``client_wins``
			Client data overwrites the server record.
		``manual``
			Row is left unresolved until an operator acts on it via the
			admin view.

		``resolved_at`` is NULL while the conflict is open.
		``resolution_strategy`` is set when the row is first written so
		that the operator knows which strategy was *applied* (server/client
		wins) or *expected* (manual).
		"""
		__allow_unmapped__ = True
		__tablename__ = "offline_sync_conflict"
		__table_args__ = (
			Index("ix_offline_conflict_model", "model_name"),
			Index("ix_offline_conflict_device", "device_id"),
			Index("ix_offline_conflict_resolved", "resolved_at"),
			{"extend_existing": True},
		)

		id = Column(Integer, primary_key=True)
		device_id = Column(String(255), nullable=False)
		model_name = Column(String(255), nullable=False)
		record_pk = Column(String(255), nullable=False)

		# Snapshot of data on the server at the time the conflict was detected
		server_data = Column(JSONB, nullable=True)
		# The payload the client attempted to write
		client_data = Column(JSONB, nullable=True)

		resolved_at = Column(DateTime(timezone=True), nullable=True)
		resolution_strategy = Column(
			String(32), nullable=False, default="server_wins"
		)

		created_at = Column(
			DateTime(timezone=True),
			nullable=False,
			default=lambda: datetime.now(timezone.utc),
		)

		def __repr__(self) -> str:
			return (
				f"<SyncConflict id={self.id} model={self.model_name} "
				f"pk={self.record_pk} strategy={self.resolution_strategy} "
				f"resolved={self.resolved_at is not None}>"
			)

	_MODELS_AVAILABLE = True

except Exception as _model_exc:  # pragma: no cover
	_MODELS_AVAILABLE = False
	log.warning("offline plugin: could not define SQLAlchemy models: %s", _model_exc)

	class SyncConflict:  # type: ignore[no-redef]
		pass

# ---------------------------------------------------------------------------
# Service Worker source (embedded, rendered as plain JS)
# ---------------------------------------------------------------------------

# Cache version is intentionally a constant string so the SW can be
# invalidated by a deploy bump. Apps may override this via app config.
_SW_TEMPLATE = """\
/* PgAppForge Offline Service Worker — generated by pgappforge.plugins.offline */
/* Cache TTL hint: {{ cache_ttl }} seconds */

const CACHE_VERSION  = '{{ cache_version }}';
const STATIC_CACHE   = `pgaf-static-${{CACHE_VERSION}}`;
const API_CACHE      = `pgaf-api-${{CACHE_VERSION}}`;
const PAGE_CACHE     = `pgaf-pages-${{CACHE_VERSION}}`;
const CACHE_TTL_MS   = {{ cache_ttl }} * 1000;

/* Asset URL patterns to precache on install */
const STATIC_PATTERNS = [
  /\\/static\\/.*(\\.(css|js|woff2?|ttf|eot|svg|png|jpg|ico))$/i,
];
const API_PATTERNS    = [/^\\/api\\//i, /\\.json$/i];

/* ── Install: open caches (no aggressive precaching — runtime only) ── */
self.addEventListener('install', event => {{
  event.waitUntil(
    caches.open(STATIC_CACHE).then(() => self.skipWaiting())
  );
}});

/* ── Activate: prune old cache versions ── */
self.addEventListener('activate', event => {{
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(k => k.startsWith('pgaf-') && ![STATIC_CACHE, API_CACHE, PAGE_CACHE].includes(k))
          .map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
}});

/* ── Fetch: strategy dispatch ── */
self.addEventListener('fetch', event => {{
  const {{ request }} = event;
  if (request.method !== 'GET') return;          /* only cache GETs       */
  const url = new URL(request.url);

  if (STATIC_PATTERNS.some(re => re.test(url.pathname))) {{
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }}

  if (API_PATTERNS.some(re => re.test(url.pathname))) {{
    event.respondWith(staleWhileRevalidate(request, API_CACHE));
    return;
  }}

  /* HTML pages: network-first, fall back to cache */
  if (request.headers.get('Accept')?.includes('text/html')) {{
    event.respondWith(networkFirst(request, PAGE_CACHE));
    return;
  }}
}});

/* ── Cache strategies ── */

async function cacheFirst(request, cacheName) {{
  const cache    = await caches.open(cacheName);
  const cached   = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) cache.put(request, response.clone());
  return response;
}}

async function staleWhileRevalidate(request, cacheName) {{
  const cache    = await caches.open(cacheName);
  const cached   = await cache.match(request);
  const fetchPr  = fetch(request).then(response => {{
    if (response.ok) {{
      const copy = response.clone();
      copy.headers?.get;                          /* keep reference alive  */
      cache.put(request, response.clone());
    }}
    return response;
  }}).catch(() => cached);                        /* network fail → stale  */
  return cached || fetchPr;
}}

async function networkFirst(request, cacheName) {{
  const cache = await caches.open(cacheName);
  try {{
    const response = await fetch(request);
    if (response.ok) cache.put(request, response.clone());
    return response;
  }} catch (_) {{
    const cached = await cache.match(request);
    return cached || Response.error();
  }}
}}
"""

# ---------------------------------------------------------------------------
# Manifest template
# ---------------------------------------------------------------------------

_MANIFEST_TEMPLATE = """\
{{
  "name": "{{ app_name }}",
  "short_name": "{{ short_name }}",
  "description": "{{ app_description }}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#2c3e50",
  "icons": [
    {{
      "src": "{{ icon_192 }}",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any maskable"
    }},
    {{
      "src": "{{ icon_512 }}",
      "sizes": "512x512",
      "type": "image/png"
    }}
  ]
}}
"""

# ---------------------------------------------------------------------------
# Offline client JS (embedded constant — ~100 lines of vanilla JS)
# ---------------------------------------------------------------------------

OFFLINE_JS = r"""
/* pgappforge-offline-client.js — auto-syncs queued mutations when reconnected */
(function (root) {
  'use strict';

  var DB_NAME    = 'pgaf_offline';
  var STORE_NAME = 'mutation_queue';
  var DB_VERSION = 1;
  var SYNC_URL   = '/offline/sync';

  /* ── IndexedDB bootstrap ── */
  var _db = null;

  function openDb() {
    return new Promise(function (resolve, reject) {
      if (_db) { resolve(_db); return; }
      var req = indexedDB.open(DB_NAME, DB_VERSION);
      req.onupgradeneeded = function (e) {
        var db    = e.target.result;
        var store = db.createObjectStore(STORE_NAME, { keyPath: 'id', autoIncrement: true });
        store.createIndex('by_timestamp', 'timestamp', { unique: false });
      };
      req.onsuccess = function (e) { _db = e.target.result; resolve(_db); };
      req.onerror   = function (e) { reject(e.target.error); };
    });
  }

  /* ── Queue a mutation for later sync ── */
  function queueMutation(model, pk, action, data, deviceId) {
    return openDb().then(function (db) {
      return new Promise(function (resolve, reject) {
        var tx    = db.transaction(STORE_NAME, 'readwrite');
        var store = tx.objectStore(STORE_NAME);
        var entry = {
          model:     model,
          pk:        pk,
          action:    action,          /* 'create' | 'update' | 'delete' */
          data:      data || {},
          timestamp: new Date().toISOString(),
          device_id: deviceId || _deviceId(),
        };
        var req = store.add(entry);
        req.onsuccess = function () { resolve(req.result); };
        req.onerror   = function () { reject(req.error); };
      });
    });
  }

  /* ── Read all queued mutations ── */
  function drainQueue() {
    return openDb().then(function (db) {
      return new Promise(function (resolve, reject) {
        var tx      = db.transaction(STORE_NAME, 'readonly');
        var store   = tx.objectStore(STORE_NAME);
        var req     = store.getAll();
        req.onsuccess = function () { resolve(req.result); };
        req.onerror   = function () { reject(req.error); };
      });
    });
  }

  /* ── Remove successfully synced mutations by id ── */
  function clearSynced(ids) {
    return openDb().then(function (db) {
      return new Promise(function (resolve, reject) {
        var tx    = db.transaction(STORE_NAME, 'readwrite');
        var store = tx.objectStore(STORE_NAME);
        var done  = 0;
        ids.forEach(function (id) {
          var req     = store.delete(id);
          req.onsuccess = function () { if (++done === ids.length) resolve(); };
          req.onerror   = function () { reject(req.error); };
        });
        if (ids.length === 0) resolve();
      });
    });
  }

  /* ── Sync queued mutations to the server ── */
  function sync() {
    if (!navigator.onLine) return Promise.resolve({ skipped: true });
    return drainQueue().then(function (ops) {
      if (!ops.length) return { applied: 0, conflicts: [], errors: [] };
      return fetch(SYNC_URL, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ operations: ops }),
      })
      .then(function (r) { return r.json(); })
      .then(function (result) {
        /* Clear only the operations the server accepted */
        var acceptedIds = ops
          .slice(0, result.applied || 0)
          .map(function (op) { return op.id; })
          .filter(Boolean);
        return clearSynced(acceptedIds).then(function () { return result; });
      });
    });
  }

  /* ── Offline indicator badge ── */
  function _updateBadge(online) {
    var badge = document.getElementById('pgaf-offline-badge');
    if (!badge) {
      badge = document.createElement('span');
      badge.id = 'pgaf-offline-badge';
      badge.style.cssText = [
        'position:fixed', 'bottom:12px', 'right:12px', 'z-index:9999',
        'background:#c0392b', 'color:#fff', 'padding:4px 10px',
        'border-radius:4px', 'font-size:12px', 'font-weight:bold',
        'display:none', 'box-shadow:0 2px 6px rgba(0,0,0,.3)',
      ].join(';');
      badge.textContent = '⚡ Offline';
      document.body.appendChild(badge);
    }
    badge.style.display = online ? 'none' : 'block';
  }

  /* ── Stable per-browser device id ── */
  function _deviceId() {
    var key = 'pgaf_device_id';
    var id  = localStorage.getItem(key);
    if (!id) {
      id = 'dev-' + Math.random().toString(36).slice(2) + Date.now().toString(36);
      localStorage.setItem(key, id);
    }
    return id;
  }

  /* ── Service Worker registration ── */
  function registerSW(swUrl) {
    if (!('serviceWorker' in navigator)) return;
    navigator.serviceWorker.register(swUrl || '/sw.js')
      .then(function (reg) { console.debug('[pgaf-offline] SW registered', reg.scope); })
      .catch(function (err) { console.warn('[pgaf-offline] SW registration failed', err); });
  }

  /* ── Init: wire online/offline events ── */
  function init(options) {
    options = options || {};
    _updateBadge(navigator.onLine);
    window.addEventListener('online',  function () {
      _updateBadge(true);
      sync().then(function (r) {
        console.debug('[pgaf-offline] sync result', r);
      }).catch(function (e) {
        console.warn('[pgaf-offline] sync error', e);
      });
    });
    window.addEventListener('offline', function () { _updateBadge(false); });
    if (options.registerSW !== false) registerSW(options.swUrl);
  }

  /* ── Public API ── */
  var PgAfOffline = {
    init:          init,
    queueMutation: queueMutation,
    sync:          sync,
    deviceId:      _deviceId,
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = PgAfOffline;
  } else {
    root.PgAfOffline = PgAfOffline;
  }
}(typeof globalThis !== 'undefined' ? globalThis : this));
"""

# ---------------------------------------------------------------------------
# Default config
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG: dict[str, Any] = {
	"PGAPPFORGE_OFFLINE_ENABLED": False,
	"PGAPPFORGE_OFFLINE_CACHE_TTL": 3600,
	"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY": "server_wins",
	# Optional per-model strategy overrides: {"MyModel": "client_wins", ...}
	"conflict_strategies": {},
	# PWA manifest customisation
	"app_name": "PgAppForge",
	"app_short_name": "PgAF",
	"app_description": "PgAppForge offline-capable application",
	"icon_192": "/static/appbuilder/img/icon-192.png",
	"icon_512": "/static/appbuilder/img/icon-512.png",
	"cache_version": "v1",
}

_CONFIG_SCHEMA: dict[str, Any] = {
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "OfflinePlugin configuration",
	"type": "object",
	"additionalProperties": False,
	"properties": {
		"PGAPPFORGE_OFFLINE_ENABLED": {
			"type": "boolean",
			"default": False,
			"description": "Master switch for offline/PWA features.",
		},
		"PGAPPFORGE_OFFLINE_CACHE_TTL": {
			"type": "integer",
			"minimum": 0,
			"default": 3600,
			"description": "Cache max-age hint (seconds) for API responses.",
		},
		"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY": {
			"type": "string",
			"enum": ["server_wins", "client_wins", "manual"],
			"default": "server_wins",
			"description": "Default conflict resolution strategy.",
		},
		"conflict_strategies": {
			"type": "object",
			"additionalProperties": {"type": "string", "enum": ["server_wins", "client_wins", "manual"]},
			"default": {},
			"description": "Per-model conflict strategy overrides (model_name -> strategy).",
		},
		"app_name": {
			"type": "string",
			"default": "PgAppForge",
			"description": "Full app name for the PWA manifest.",
		},
		"app_short_name": {
			"type": "string",
			"default": "PgAF",
			"description": "Short app name for the PWA manifest (≤12 chars recommended).",
		},
		"app_description": {
			"type": "string",
			"default": "PgAppForge offline-capable application",
		},
		"icon_192": {
			"type": "string",
			"default": "/static/appbuilder/img/icon-192.png",
			"description": "URL for 192×192 PWA icon.",
		},
		"icon_512": {
			"type": "string",
			"default": "/static/appbuilder/img/icon-512.png",
			"description": "URL for 512×512 PWA icon.",
		},
		"cache_version": {
			"type": "string",
			"default": "v1",
			"description": "Cache key version string. Bump to force SW cache invalidation.",
		},
	},
}

# ---------------------------------------------------------------------------
# Blueprint — serves sw.js, manifest.json, and the sync endpoint
# ---------------------------------------------------------------------------

def _build_blueprint(plugin: "OfflinePlugin") -> Blueprint:
	"""
	Build and return the Flask Blueprint for the offline plugin.

	Separated from the class so it can be unit-tested without a full
	AppBuilder instance.
	"""
	bp = Blueprint(
		"pgaf_offline",
		__name__,
		url_prefix="",          # sw.js must be served at the root scope
	)

	@bp.route("/sw.js")
	def service_worker() -> Response:
		"""Serve the generated Service Worker."""
		cfg = plugin.config
		body = (
			_SW_TEMPLATE
			.replace("{{ cache_ttl }}", str(cfg.get("PGAPPFORGE_OFFLINE_CACHE_TTL", 3600)))
			.replace("{{ cache_version }}", str(cfg.get("cache_version", "v1")))
		)
		resp = make_response(body, 200)
		resp.headers["Content-Type"] = "application/javascript"
		resp.headers["Service-Worker-Allowed"] = "/"
		resp.headers["Cache-Control"] = "no-cache, no-store"
		return resp

	@bp.route("/manifest.json")
	def manifest() -> Response:
		"""Serve the PWA Web App Manifest."""
		cfg = plugin.config
		body = (
			_MANIFEST_TEMPLATE
			.replace("{{ app_name }}",        cfg.get("app_name", "PgAppForge"))
			.replace("{{ short_name }}",       cfg.get("app_short_name", "PgAF"))
			.replace("{{ app_description }}",  cfg.get("app_description", ""))
			.replace("{{ icon_192 }}",         cfg.get("icon_192", "/static/appbuilder/img/icon-192.png"))
			.replace("{{ icon_512 }}",         cfg.get("icon_512", "/static/appbuilder/img/icon-512.png"))
		)
		resp = make_response(body, 200)
		resp.headers["Content-Type"] = "application/manifest+json"
		resp.headers["Cache-Control"] = "no-cache"
		return resp

	@bp.route("/offline/sync", methods=["POST"])
	def sync_endpoint() -> Response:
		"""
		Batch-apply client operations queued while offline.

		Request body (JSON)::

		    {
		      "operations": [
		        {
		          "model":     "Employee",
		          "pk":        "42",
		          "action":    "update",     // create | update | delete
		          "data":      {...},
		          "timestamp": "2026-05-30T12:00:00Z",
		          "device_id": "dev-abc123"
		        }
		      ]
		    }

		Response::

		    {
		      "applied":   N,
		      "conflicts": [{...}],
		      "errors":    [{...}]
		    }
		"""
		if not plugin.config.get("PGAPPFORGE_OFFLINE_ENABLED", False):
			return jsonify({"error": "offline sync is disabled"}), 503

		payload = request.get_json(silent=True) or {}
		operations: list[dict[str, Any]] = payload.get("operations", [])

		applied:   int             = 0
		conflicts: list[dict[str, Any]] = []
		errors:    list[dict[str, Any]] = []

		for op in operations:
			try:
				result = plugin._apply_operation(op)
				if result == "applied":
					applied += 1
				elif result == "conflict":
					conflicts.append({
						"model":  op.get("model"),
						"pk":     op.get("pk"),
						"action": op.get("action"),
					})
			except Exception as exc:
				log.error("offline plugin: sync error for op %s: %s", op, exc)
				errors.append({
					"model":   op.get("model"),
					"pk":      op.get("pk"),
					"action":  op.get("action"),
					"message": str(exc),
				})

		log.info(
			"offline plugin: sync — applied=%d conflicts=%d errors=%d",
			applied, len(conflicts), len(errors),
		)
		return jsonify({"applied": applied, "conflicts": conflicts, "errors": errors})

	return bp

# ---------------------------------------------------------------------------
# Admin view (conflict management)
# ---------------------------------------------------------------------------

_CONFLICT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Offline Sync Conflicts — PgAppForge</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <style>
    body { padding-top: 60px; }
    .hero { background:#f5f5f5; padding:30px 20px; border-radius:6px;
            margin-bottom:24px; border-left:4px solid #e74c3c; }
  </style>
</head>
<body>
<div class="container">
  <div class="hero">
    <h2><span class="glyphicon glyphicon-transfer"></span> Offline Sync Conflicts</h2>
    <p class="lead">Review and resolve mutations that conflicted during offline sync.</p>
    <span class="label label-success">Plugin active</span>
    <span class="label label-default">strategy: {{ strategy }}</span>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-danger">
        <div class="panel-heading"><h4>Open Conflicts</h4></div>
        <div class="panel-body">
          Unresolved conflict rows from <code>offline_sync_conflict</code>.
          Resolve by choosing server or client data as authoritative.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h4>Resolved History</h4></div>
        <div class="panel-body">
          Conflicts resolved automatically by the configured strategy or
          manually by an operator.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-info">
        <div class="panel-heading"><h4>Sync Log</h4></div>
        <div class="panel-body">
          Server-side log of all sync batches: device, timestamp,
          applied / conflict / error counts.
        </div>
      </div>
    </div>
  </div>
  <div class="alert alert-info">
    <strong>Offline client JS:</strong>
    Include <code>/static/appbuilder/js/pgappforge-offline.js</code> in your base
    template and call <code>PgAfOffline.init()</code> to activate the offline badge
    and auto-sync on reconnect.
  </div>
</div>
</body>
</html>
"""


class OfflineSyncConflictView(BaseView):
	"""
	Admin view for reviewing and resolving sync conflicts.

	Mounted at ``/offline/conflicts/`` by OfflinePlugin.register_views().
	Requires the ``can_view`` permission on this view.
	"""

	route_base = "/offline/conflicts"
	default_view = "index"

	@expose("/")
	@has_access
	def index(self):
		strategy = self.appbuilder.app.config.get(
			"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY", "server_wins"
		)
		html = _CONFLICT_TEMPLATE.replace("{{ strategy }}", strategy)
		return make_response(html, 200)


# ---------------------------------------------------------------------------
# OfflinePlugin
# ---------------------------------------------------------------------------

class OfflinePlugin(BasePlugin):
	"""
	Offline-first PWA plugin for PgAppForge.

	Features
	--------
	- Service Worker (``/sw.js``) with three caching strategies:
	  - static assets   → cache-first
	  - API GET routes  → stale-while-revalidate
	  - HTML pages      → network-first
	- ``/manifest.json`` for PWA installability
	- ``POST /offline/sync`` endpoint for batched operation replay
	- ``SyncConflict`` SQLAlchemy model for conflict persistence
	- ``OFFLINE_JS`` vanilla-JS helper (~100 lines) that queues mutations
	  in IndexedDB and auto-syncs when ``navigator.onLine`` fires

	Lifecycle
	---------
	1. ``initialize()``     — merge config defaults, validate strategy
	2. ``register_views()`` — register blueprint + admin view
	3. ``register_models()``— return [SyncConflict]
	4. ``_apply_operation()``— internal per-operation sync logic
	5. ``deactivate()``     — clean up via BasePlugin
	"""

	# ------------------------------------------------------------------
	# Metadata
	# ------------------------------------------------------------------

	@property
	def metadata(self) -> PluginMetadata:
		return PluginMetadata(
			name="offline",
			version="0.1.0",
			description=(
				"Offline-first PWA support: Service Worker, Web App Manifest, "
				"IndexedDB mutation queue, and server-side batch sync."
			),
			author="PgAppForge Contributors",
			tags=["offline", "pwa", "sync", "service-worker", "indexeddb"],
			priority=PluginPriority.NORMAL,
			permissions=[
				"can_view_OfflineSyncConflictView",
			],
			safe_mode_compatible=True,
			example_config={
				"PGAPPFORGE_OFFLINE_ENABLED": True,
				"PGAPPFORGE_OFFLINE_CACHE_TTL": 3600,
				"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY": "server_wins",
			},
		)

	# ------------------------------------------------------------------
	# Lifecycle
	# ------------------------------------------------------------------

	def initialize(self) -> None:
		"""Merge config defaults and validate the conflict strategy."""
		merged = {**_DEFAULT_CONFIG, **self.config}

		# Also pull from Flask app config if available
		app_cfg = {}
		try:
			app = self.appbuilder.get_app
			for key in (
				"PGAPPFORGE_OFFLINE_ENABLED",
				"PGAPPFORGE_OFFLINE_CACHE_TTL",
				"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY",
			):
				if key in app.config:
					app_cfg[key] = app.config[key]
		except Exception:
			pass

		# App config < plugin-level config (explicit caller wins)
		self.config = {**merged, **app_cfg, **{k: v for k, v in self.config.items() if k in merged}}
		# Re-merge so explicit constructor config takes precedence over app config
		self.config = {**merged, **app_cfg}
		# Then re-apply any constructor-supplied keys on top
		for k, v in merged.items():
			if k not in _DEFAULT_CONFIG or v != _DEFAULT_CONFIG[k]:
				self.config[k] = v

		self._validate_config()

		enabled = self.config.get("PGAPPFORGE_OFFLINE_ENABLED", False)
		log.info(
			"offline plugin: initialized (enabled=%s strategy=%s cache_ttl=%ss)",
			enabled,
			self.config.get("PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY"),
			self.config.get("PGAPPFORGE_OFFLINE_CACHE_TTL"),
		)

	def register_views(self) -> None:
		"""Register the Flask blueprint and the conflict admin view."""
		bp = _build_blueprint(self)
		self.register_blueprint(bp)

		self.add_view(
			OfflineSyncConflictView,
			"Sync Conflicts",
			icon="fa-exchange",
			category="Offline",
			category_icon="fa-wifi",
		)
		log.info("offline plugin: blueprint and views registered")

	def register_models(self) -> list:
		"""Return SQLAlchemy model classes for Alembic autogenerate."""
		if _MODELS_AVAILABLE:
			return [SyncConflict]
		log.warning("offline plugin: SQLAlchemy models unavailable — skipping")
		return []

	def get_config_schema(self) -> dict:
		"""JSON Schema for the admin plugin settings form."""
		return _CONFIG_SCHEMA

	# ------------------------------------------------------------------
	# Operation application (called by the sync endpoint)
	# ------------------------------------------------------------------

	def _apply_operation(self, op: dict[str, Any]) -> str:
		"""
		Apply a single offline operation to the database.

		Returns ``"applied"`` on success or ``"conflict"`` when the
		configured strategy routes the operation to the conflict table.

		Conflict resolution
		-------------------
		``server_wins``
			Discard client data; record the conflict row as resolved.
		``client_wins``
			Overwrite server record; resolve the conflict immediately.
		``manual``
			Write an unresolved SyncConflict row; return ``"conflict"``
			so the caller excludes it from the applied count.

		Args:
			op: Single operation dict with keys model, pk, action, data,
			    timestamp, device_id.

		Returns:
			``"applied"`` | ``"conflict"``
		"""
		model_name: str      = op.get("model", "")
		record_pk:  str      = str(op.get("pk", ""))
		action:     str      = op.get("action", "update")
		data:       dict     = op.get("data") or {}
		device_id:  str      = op.get("device_id", "unknown")
		timestamp:  str      = op.get("timestamp", "")

		# Resolve strategy: per-model override takes precedence
		default_strategy: str = self.config.get(
			"PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY", "server_wins"
		)
		strategy: str = (
			self.config.get("conflict_strategies", {}).get(model_name)
			or default_strategy
		)

		if not _MODELS_AVAILABLE:
			log.warning(
				"offline plugin: models unavailable — cannot apply op %s/%s",
				model_name, record_pk,
			)
			return "applied"

		try:
			db_session = self.appbuilder.get_session
		except Exception as exc:
			log.error("offline plugin: cannot get DB session: %s", exc)
			raise

		# Resolve the model class by name from SQLAlchemy's mapper registry
		model_cls = _resolve_model(model_name)

		if model_cls is None:
			log.warning("offline plugin: unknown model %r — skipping op", model_name)
			return "applied"

		# Fetch the current server record
		server_record = db_session.get(model_cls, _coerce_pk(model_cls, record_pk))
		server_data   = _record_to_dict(server_record) if server_record else None

		# Determine if this is a genuine conflict:
		# A conflict exists when the server record has been touched after
		# the client's last known timestamp for this record.
		is_conflict = _detect_conflict(server_record, timestamp)

		if is_conflict:
			conflict = SyncConflict(
				device_id=device_id,
				model_name=model_name,
				record_pk=record_pk,
				server_data=server_data,
				client_data=data,
				resolution_strategy=strategy,
			)

			if strategy == "server_wins":
				# Discard client change; mark conflict as resolved immediately
				conflict.resolved_at = datetime.now(timezone.utc)
				db_session.add(conflict)
				db_session.commit()
				log.debug(
					"offline plugin: server_wins conflict resolved for %s/%s",
					model_name, record_pk,
				)
				return "applied"

			elif strategy == "client_wins":
				# Apply client data, then mark conflict resolved
				_apply_data(db_session, model_cls, server_record, record_pk, action, data)
				conflict.resolved_at = datetime.now(timezone.utc)
				db_session.add(conflict)
				db_session.commit()
				log.debug(
					"offline plugin: client_wins applied for %s/%s",
					model_name, record_pk,
				)
				return "applied"

			else:  # "manual"
				db_session.add(conflict)
				db_session.commit()
				log.info(
					"offline plugin: manual conflict queued for %s/%s",
					model_name, record_pk,
				)
				return "conflict"

		# No conflict — apply the operation directly
		_apply_data(db_session, model_cls, server_record, record_pk, action, data)
		db_session.commit()
		log.debug("offline plugin: applied %s on %s/%s", action, model_name, record_pk)
		return "applied"

	# ------------------------------------------------------------------
	# Config validation
	# ------------------------------------------------------------------

	def _validate_config(self) -> None:
		strategy = self.config.get("PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY", "server_wins")
		valid = {"server_wins", "client_wins", "manual"}
		if strategy not in valid:
			raise ValueError(
				f"offline plugin: invalid PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY {strategy!r}; "
				f"must be one of {sorted(valid)}"
			)
		for model_name, s in self.config.get("conflict_strategies", {}).items():
			if s not in valid:
				raise ValueError(
					f"offline plugin: invalid strategy {s!r} for model {model_name!r}; "
					f"must be one of {sorted(valid)}"
				)
		ttl = self.config.get("PGAPPFORGE_OFFLINE_CACHE_TTL", 3600)
		if not isinstance(ttl, int) or ttl < 0:
			raise ValueError(
				f"offline plugin: PGAPPFORGE_OFFLINE_CACHE_TTL must be a non-negative integer, got {ttl!r}"
			)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _resolve_model(model_name: str):
	"""
	Look up a SQLAlchemy mapped class by its ``__name__``.

	Searches the SQLAlchemy mapper registry; returns None if not found.
	"""
	try:
		from sqlalchemy.orm import class_mapper
		from sqlalchemy import inspect as sa_inspect
		from sqlalchemy.orm import DeclarativeBase
		# Walk the mapper registry
		from sqlalchemy.orm import registry as _registry_type
		import sqlalchemy.orm as _orm
		for mapper in _orm.mapperlib._mapper_registry:  # type: ignore[attr-defined]
			cls = mapper.class_
			if cls.__name__ == model_name:
				return cls
	except Exception:
		pass
	# Fallback: try iterating SQLAlchemy's global mapper registry
	try:
		import sqlalchemy
		from sqlalchemy.orm import DeclarativeMeta
		import gc
		for obj in gc.get_objects():
			if isinstance(obj, DeclarativeMeta) and getattr(obj, "__name__", "") == model_name:
				return obj
	except Exception:
		pass
	return None


def _coerce_pk(model_cls, pk_str: str):
	"""
	Convert a string PK to the column's Python type.

	Only handles integer PKs for now; returns the string as-is for others.
	"""
	try:
		from sqlalchemy import inspect as sa_inspect
		mapper = sa_inspect(model_cls)
		pk_cols = mapper.primary_key
		if pk_cols:
			col_type = pk_cols[0].type
			from sqlalchemy import Integer as _IntType
			if isinstance(col_type, _IntType):
				return int(pk_str)
	except Exception:
		pass
	return pk_str


def _record_to_dict(record) -> dict[str, Any]:
	"""Shallow-serialise a SQLAlchemy model instance to a plain dict."""
	try:
		from sqlalchemy import inspect as sa_inspect
		mapper = sa_inspect(type(record))
		return {col.key: getattr(record, col.key) for col in mapper.column_attrs}
	except Exception:
		return {}


def _detect_conflict(server_record, client_timestamp: str) -> bool:
	"""
	Return True if the server record was modified after ``client_timestamp``.

	Uses the ``changed_on`` or ``updated_at`` column when present.
	Falls back to False (no conflict) when the record is new or the
	timestamp cannot be parsed.
	"""
	if server_record is None:
		return False
	if not client_timestamp:
		return False

	server_ts = (
		getattr(server_record, "changed_on", None)
		or getattr(server_record, "updated_at", None)
	)
	if server_ts is None:
		return False

	try:
		from datetime import datetime, timezone
		client_dt = datetime.fromisoformat(client_timestamp.rstrip("Z")).replace(
			tzinfo=timezone.utc
		)
		if server_ts.tzinfo is None:
			server_ts = server_ts.replace(tzinfo=timezone.utc)
		return server_ts > client_dt
	except Exception:
		return False


def _apply_data(db_session, model_cls, server_record, pk_str: str, action: str, data: dict) -> None:
	"""
	Apply ``create``, ``update``, or ``delete`` to a model record.

	- ``create`` / ``update``: upsert field values from *data*
	- ``delete``: delete the record if it exists
	"""
	if action == "delete":
		if server_record is not None:
			db_session.delete(server_record)
		return

	if server_record is None:
		# create
		try:
			record = model_cls()
			for key, val in data.items():
				if hasattr(record, key):
					setattr(record, key, val)
			db_session.add(record)
		except Exception as exc:
			log.error("offline plugin: create failed for %s: %s", model_cls.__name__, exc)
			raise
	else:
		# update — only touch columns that exist on the model
		for key, val in data.items():
			if hasattr(server_record, key) and key not in ("id", "pk"):
				setattr(server_record, key, val)


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def create_plugin(appbuilder, config: dict[str, Any] | None = None) -> OfflinePlugin:
	"""
	Construct and return an OfflinePlugin bound to *appbuilder*.

	Does **not** call ``activate()`` — the caller controls the lifecycle::

	    plugin = create_plugin(appbuilder, config={
	        "PGAPPFORGE_OFFLINE_ENABLED": True,
	        "PGAPPFORGE_OFFLINE_CONFLICT_STRATEGY": "client_wins",
	    })
	    plugin.activate()

	Args:
	    appbuilder: PgAppForge / AppBuilder instance.
	    config:     Optional config dict merged over built-in defaults.

	Returns:
	    An uninitialised OfflinePlugin ready for ``activate()``.
	"""
	return OfflinePlugin(appbuilder, config=config or {})


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
	# Plugin class + factory
	"OfflinePlugin",
	"create_plugin",
	# Model
	"SyncConflict",
	# View
	"OfflineSyncConflictView",
	# Embedded JS helper
	"OFFLINE_JS",
	# Capability flag
	"_MODELS_AVAILABLE",
]
