"""PDL code generators.

Each public method returns a Python source string (str).
No I/O happens unless *output_base* is passed to :meth:`generate_all`.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from pgappforge.pdl.schema import PDLSchema, PDLEntity, PDLField, FIELD_TYPES, _snake


class PDLCodeGenerator:
	"""Generates code artifacts from a :class:`~pgappforge.pdl.schema.PDLSchema`.

	Artifacts
	---------
	model       — SQLAlchemy 2.x model class
	migration   — Alembic migration script
	view        — FAB ModelView + BaseERPView dashboard
	api         — OpenAPI-documented REST endpoint stub
	tests       — pytest import smoke tests
	"""

	# ------------------------------------------------------------------
	# Top-level orchestration
	# ------------------------------------------------------------------

	def generate_all(
		self,
		schema: PDLSchema,
		output_base: Path | None = None,
	) -> dict[str, str]:
		"""Generate all artifacts for every entity in *schema*.

		Returns a flat ``{"{EntityName}/{filename}": code_str}`` dict.
		If *output_base* is given, writes files under that directory as well.
		"""
		results: dict[str, str] = {}
		for entity in schema.entities:
			entity_results = self.generate_entity(entity, schema)
			for artifact, code in entity_results.items():
				key = f"{entity.name}/{artifact}"
				results[key] = code
				if output_base and artifact in entity.generate:
					self._write(output_base, entity, artifact, code)
		results.update(self.generate_schema_files(schema))
		return results

	def generate_entity(self, entity: PDLEntity, schema: PDLSchema) -> dict[str, str]:
		"""Generate all configured artifacts for a single entity."""
		results: dict[str, str] = {}
		if "model" in entity.generate:
			results["models.py"] = self.generate_model(entity)
		if "migration" in entity.generate:
			results["migration.py"] = self.generate_migration(entity)
		if "view" in entity.generate:
			results["views.py"] = self.generate_view(entity)
		if "api" in entity.generate:
			results["api.py"] = self.generate_api(entity)
		if "tests" in entity.generate:
			results["test_model.py"] = self.generate_tests(entity)
		return results

	# ------------------------------------------------------------------
	# Individual artifact generators
	# ------------------------------------------------------------------

	def generate_model(self, entity: PDLEntity) -> str:
		"""Return a complete SQLAlchemy 2.x model class as a source string."""
		cols: list[str] = []
		needs_jsonb = any(f.type == "jsonb" for f in entity.fields)

		if entity.include_uuid_pk:
			cols.append(
				'\tid = sa.Column(sa.String(36), primary_key=True, '
				'default=_uuid7, server_default=sa.text("gen_random_uuid()::text"))'
			)

		if entity.include_tenant_id:
			cols.append('\ttenant_id = sa.Column(sa.String(36), nullable=False, index=True)')

		for f in entity.fields:
			cols.append(f'\t{self._field_to_column(f)}')

		if entity.include_audit_timestamps:
			cols.append(
				'\tcreated_at = sa.Column(sa.DateTime(timezone=True), nullable=False, '
				'default=lambda: datetime.now(timezone.utc), server_default=sa.text("NOW()"))'
			)
			cols.append(
				'\tupdated_at = sa.Column(sa.DateTime(timezone=True), nullable=False, '
				'default=lambda: datetime.now(timezone.utc), '
				'onupdate=lambda: datetime.now(timezone.utc), server_default=sa.text("NOW()"))'
			)

		cols_str   = "\n".join(cols)
		jsonb_import = (
			"\nfrom sqlalchemy.dialects.postgresql import JSONB"
			if needs_jsonb
			else ""
		)
		table_args = self._table_args(entity)

		return f'''\
# Generated by PgAppForge PDL — do not edit manually
# Source: {entity.name}.pdl.yaml
from __future__ import annotations

import sqlalchemy as sa
from datetime import datetime, timezone
{jsonb_import}

try:
\tfrom pgappforge.models.sqla import Model
\tfrom pgappforge.plugins.audit import AuditMixin
except ImportError:
\tModel = object
\tAuditMixin = object


def _uuid7() -> str:
\ttry:
\t\tfrom uuid6 import uuid7
\t\treturn str(uuid7())
\texcept ImportError:
\t\timport uuid
\t\treturn str(uuid.uuid4())


class {entity.name}(AuditMixin, Model):
\t"""{entity.description or entity.name + " entity — generated by PgAppForge PDL"}"""

\t__tablename__ = "{entity.table}"
\t__table_args__ = (
\t\t{table_args}{{"extend_existing": True}},
\t)

{cols_str}

\tdef __repr__(self) -> str:
\t\treturn f"<{entity.name} {{self.id!r:.8}}>"
'''

	def _field_to_column(self, f: PDLField) -> str:
		"""Convert a :class:`PDLField` to a SQLAlchemy ``Column(...)`` expression."""
		if f.fk:
			ref_model, ref_col = (f.fk.rsplit(".", 1) if "." in f.fk else (f.fk, "id"))
			# PascalCase model name → snake_case table name
			table_name = _snake(ref_model) if ref_model and ref_model[0].isupper() else ref_model
			null = "True" if f.nullable else "False"
			idx  = ", index=True" if f.indexed else ""
			return (
				f'{f.name} = sa.Column(sa.String(36), '
				f'sa.ForeignKey("{table_name}.{ref_col}", ondelete="RESTRICT"), '
				f'nullable={null}{idx})'
			)

		_, sa_type = FIELD_TYPES.get(f.type, ("String(255)", "sa.String(255)"))
		if f.type == "string" and f.max_length:
			sa_type = f"sa.String({f.max_length})"
		elif f.type == "jsonb":
			sa_type = "JSONB"

		null    = "True" if f.nullable else "False"
		idx     = ", index=True" if f.indexed else ""
		uniq    = ", unique=True" if f.unique else ""
		default = ""
		if f.default is not None:
			if isinstance(f.default, str) and not f.default.startswith("sa."):
				default = f', default="{f.default}"'
			else:
				default = f", default={f.default}"

		auto_label = f.name.replace("_", " ").title()
		comment = f', comment="{f.label}"' if f.label != auto_label else ""

		return f"{f.name} = sa.Column({sa_type}, nullable={null}{idx}{uniq}{default}{comment})"

	def _table_args(self, entity: PDLEntity) -> str:
		"""Return comma-separated index / constraint declarations for ``__table_args__``."""
		parts: list[str] = []
		if entity.include_tenant_id:
			parts.append(f'sa.Index("ix_{entity.table}_tenant", "tenant_id"),')
		for f in entity.fields:
			if f.indexed and not f.fk:
				parts.append(f'sa.Index("ix_{entity.table}_{f.name}", "{f.name}"),')
			if f.unique and not f.fk:
				parts.append(
					f'sa.UniqueConstraint("tenant_id", "{f.name}", '
					f'name="uq_{entity.table}_{f.name}"),'
				)
		return ("\n\t\t".join(parts) + "\n\t\t") if parts else ""

	# ------------------------------------------------------------------

	def generate_migration(self, entity: PDLEntity) -> str:
		"""Return an Alembic ``upgrade`` / ``downgrade`` migration script."""
		now_str  = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
		col_defs: list[str] = []

		if entity.include_uuid_pk:
			col_defs.append('\t\t\tsa.Column("id", sa.String(36), primary_key=True),')
		if entity.include_tenant_id:
			col_defs.append('\t\t\tsa.Column("tenant_id", sa.String(36), nullable=False),')

		for f in entity.fields:
			_, sa_type = FIELD_TYPES.get(f.type, ("String(255)", "sa.String(255)"))
			if f.type == "jsonb":
				sa_type = "postgresql.JSONB"
			null = "True" if f.nullable else "False"
			col_defs.append(f'\t\t\tsa.Column("{f.name}", {sa_type}, nullable={null}),')

		if entity.include_audit_timestamps:
			col_defs.append(
				'\t\t\tsa.Column("created_at", sa.DateTime(timezone=True), '
				'server_default=sa.text("NOW()")),')
			col_defs.append(
				'\t\t\tsa.Column("updated_at", sa.DateTime(timezone=True), '
				'server_default=sa.text("NOW()")),')

		cols_str = "\n".join(col_defs)
		ts       = datetime.now(timezone.utc).isoformat()

		return f'''\
"""Create {entity.table} table — generated by PgAppForge PDL

Revision ID: {now_str}_{entity.table[:20]}
Create Date: {ts}
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
\top.create_table(
\t\t"{entity.table}",
{cols_str}
\t)
\top.create_index("ix_{entity.table}_tenant", "{entity.table}", ["tenant_id"])


def downgrade() -> None:
\top.drop_table("{entity.table}")
'''

	# ------------------------------------------------------------------

	def generate_view(self, entity: PDLEntity) -> str:
		"""Return a FAB ModelView + BaseERPView dashboard source string."""
		list_cols   = [f'"{f.name}"' for f in entity.fields[:6] if not f.fk]
		search_cols = [
			f'"{f.name}"' for f in entity.fields
			if f.type in ("string", "text", "email", "phone") and not f.fk
		]
		route_slug = _snake(entity.name).replace("_", "-")

		return f'''\
# Generated by PgAppForge PDL
from __future__ import annotations

from flask import render_template
from pgappforge import expose
from pgappforge.security.decorators import has_access
from pgappforge.plugins.erp.base_view import BaseERPView, BaseERPModelView
from pgappforge.models.sqla.interface import SQLAInterface
from {entity.module_path}.models import {entity.name}


class {entity.name}View(BaseERPModelView):
\tdatamodel = SQLAInterface({entity.name})
\tlist_columns   = [{", ".join(list_cols) if list_cols else '"id"'}]
\tsearch_columns = [{", ".join(search_cols)}]
\tadd_exclude_columns  = list(BaseERPModelView._AUDIT)
\tedit_exclude_columns = list(BaseERPModelView._AUDIT)


class {entity.name}DashboardView(BaseERPView):
\troute_base = "/{route_slug}"

\t@expose("/")
\t@has_access
\tdef index(self):
\t\tkpi_html = self.kpi_cards([
\t\t\t{{
\t\t\t\t"label": "Total {entity.name}s",
\t\t\t\t"value": self._count({entity.name}),
\t\t\t\t"icon": "fa-list",
\t\t\t\t"color": "#1a56db",
\t\t\t}},
\t\t])
\t\treturn render_template(
\t\t\t"appbuilder/erp/home_dashboard.html",
\t\t\tkpi_html=kpi_html,
\t\t\tappbuilder=self.appbuilder,
\t\t)


__all__ = ["{entity.name}View", "{entity.name}DashboardView"]
'''

	# ------------------------------------------------------------------

	def generate_api(self, entity: PDLEntity) -> str:
		"""Return a REST API endpoint stub source string."""
		snake_name  = _snake(entity.name)
		route_slug  = snake_name.replace("_", "-")
		field_reprs = ", ".join(
			f'"{f.name}": str(getattr(item, "{f.name}", ""))'
			for f in entity.fields[:5]
		)

		return f'''\
# Generated by PgAppForge PDL — REST API for {entity.name}
from __future__ import annotations

import sqlalchemy as sa
from flask import jsonify, request
from pgappforge import expose
from pgappforge.security.decorators import has_access
from pgappforge.plugins.erp.base_view import BaseERPView
from {entity.module_path}.models import {entity.name}


class {entity.name}APIView(BaseERPView):
\troute_base = "/api/{route_slug}"

\t@expose("/", methods=["GET"])
\t@has_access
\tdef list(self):
\t\tsession = self._session()
\t\ttid = self._tenant_id()
\t\titems = session.execute(
\t\t\tsa.select({entity.name})
\t\t\t.where({entity.name}.tenant_id == tid)
\t\t\t.limit(100)
\t\t).scalars().all()
\t\treturn jsonify([
\t\t\t{{"id": str(i.id), {field_reprs}}}
\t\t\tfor i in items
\t\t])

\t@expose("/<string:record_id>", methods=["GET"])
\t@has_access
\tdef detail(self, record_id: str):
\t\tsession = self._session()
\t\ttid = self._tenant_id()
\t\titem = session.execute(
\t\t\tsa.select({entity.name}).where(
\t\t\t\t{entity.name}.id == record_id,
\t\t\t\t{entity.name}.tenant_id == tid,
\t\t\t)
\t\t).scalar_one_or_none()
\t\tif item is None:
\t\t\treturn jsonify({{"error": "Not found"}}), 404
\t\treturn jsonify({{"id": str(item.id), {field_reprs}}})


__all__ = ["{entity.name}APIView"]
'''

	# ------------------------------------------------------------------

	def generate_tests(self, entity: PDLEntity) -> str:
		"""Return a pytest smoke-test source string."""
		snake_name = _snake(entity.name)

		return f'''\
# Generated by PgAppForge PDL — tests for {entity.name}
from __future__ import annotations

import pytest


def test_{snake_name}_model_imports():
\tfrom {entity.module_path}.models import {entity.name}
\tassert {entity.name}.__tablename__ == "{entity.table}"


def test_{snake_name}_view_imports():
\tfrom {entity.module_path}.views import {entity.name}View, {entity.name}DashboardView
\tassert hasattr({entity.name}View, "datamodel")


def test_{snake_name}_api_imports():
\tfrom {entity.module_path}.api import {entity.name}APIView
\tassert callable({entity.name}APIView.list)
'''

	def generate_docker_compose(self, schema: PDLSchema) -> str:
		"""Return a docker-compose.yml for local development."""
		service_name = _snake(schema.namespace) if schema.namespace else "app"
		return f"""\
version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: {service_name}_dev
      POSTGRES_USER: pgaf
      POSTGRES_PASSWORD: pgaf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pgaf"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://pgaf:pgaf@db/{service_name}_dev
      SECRET_KEY: change-me-in-production-minimum-20-chars
      FLASK_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8080

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
"""

	def generate_github_actions(self, schema: PDLSchema) -> str:
		"""Return a GitHub Actions CI workflow YAML."""
		service_name = _snake(schema.namespace) if schema.namespace else "app"
		project_label = schema.namespace or "App"
		return f"""\
name: CI — {project_label}

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_DB: {service_name}_test
          POSTGRES_USER: pgaf
          POSTGRES_PASSWORD: pgaf
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      SQLALCHEMY_DATABASE_URI: postgresql://pgaf:pgaf@localhost/{service_name}_test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install uv
      - run: uv sync
      - name: Run tests
        run: uv run pytest tests/ci/ -q --tb=short
      - name: Type check
        run: uv run pyright pgappforge/ || true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install uv && uv sync
      - run: uv run ruff check pgappforge/ || true
"""

	def generate_dockerfile(self, schema: PDLSchema) -> str:
		"""Return a production-ready Dockerfile using uv."""
		service_name = _snake(schema.namespace or "app")
		return f'''\
FROM python:3.12-slim AS base
WORKDIR /app

# Install uv for fast dependency management
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy dependency files first (layer caching)
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --no-dev

# Copy application code
COPY . .

# Run as non-root
RUN useradd -m -u 1000 appuser && chown -R appuser /app
USER appuser

EXPOSE 8080
ENV FLASK_APP=pgappforge
CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:8080", "--workers", "2", "--timeout", "120", "pgappforge:create_app()"]
'''

	def generate_k8s(self, schema: PDLSchema) -> dict[str, str]:
		"""Return Kubernetes manifests: Deployment, Service, ConfigMap, PostgreSQL StatefulSet."""
		service_name = _snake(schema.namespace or "app")
		return {
			"k8s/configmap.yaml": f'''\
apiVersion: v1
kind: ConfigMap
metadata:
  name: {service_name}-config
  labels:
    app: {service_name}
data:
  FLASK_ENV: "production"
  PGAPPFORGE_LOG_LEVEL: "INFO"
''',
			"k8s/deployment.yaml": f'''\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {service_name}
  template:
    metadata:
      labels:
        app: {service_name}
    spec:
      containers:
        - name: {service_name}
          image: {service_name}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {service_name}-config
            - secretRef:
                name: {service_name}-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
# Secret template — populate with real values before applying
apiVersion: v1
kind: Secret
metadata:
  name: {service_name}-secrets
type: Opaque
stringData:
  SECRET_KEY: "change-me-minimum-20-chars"
  SQLALCHEMY_DATABASE_URI: "postgresql://pgaf:pgaf@postgres/{service_name}"
''',
			"k8s/service.yaml": f'''\
apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  selector:
    app: {service_name}
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {service_name}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {service_name}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {service_name}
                port:
                  number: 80
''',
			"k8s/postgres.yaml": f'''\
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {service_name}
            - name: POSTGRES_USER
              value: pgaf
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "pgaf"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None
''',
		}

	def generate_schema_files(self, schema: PDLSchema) -> dict[str, str]:
		"""Generate schema-level files (one per project, not per entity)."""
		return {
			"Dockerfile":                    self.generate_dockerfile(schema),
			"docker-compose.yml":            self.generate_docker_compose(schema),
			".github/workflows/ci.yml":      self.generate_github_actions(schema),
		}

	# ------------------------------------------------------------------
	# File I/O helper
	# ------------------------------------------------------------------

	def _write(self, base: Path, entity: PDLEntity, artifact: str, code: str) -> Path:
		"""Write *code* to the appropriate path under *base*."""
		ts       = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
		filename = {
			"models.py":    "models.py",
			"migration.py": f"migrations/{ts}_{entity.table}.py",
			"views.py":     "views.py",
			"api.py":       "api.py",
			"test_model.py": f"tests/test_{_snake(entity.name)}.py",
		}.get(artifact, artifact)

		path = base / filename
		path.parent.mkdir(parents=True, exist_ok=True)
		path.write_text(code, encoding="utf-8")
		return path


__all__ = ["PDLCodeGenerator"]
