"""
Smart Code Regeneration Engine for PgForge

This module provides intelligent code regeneration capabilities that preserve
custom code modifications while updating generated code based on schema changes.

Features:
- AST-based code analysis and manipulation
- Custom code detection and preservation
- Intelligent merging strategies
- Conflict resolution with human-readable reports
- Safe backup and rollback mechanisms
- Performance-optimized regeneration
"""

import ast
import os
import re
import json
import time
import hashlib
import difflib
from typing import Dict, List, Optional, Any, Tuple, Set, Union
from dataclasses import dataclass, asdict, field
from enum import Enum
from pathlib import Path
import logging
from datetime import datetime
import shutil
import tempfile

logger = logging.getLogger(__name__)


class CodeElementType(Enum):
    """Types of code elements that can be analyzed."""
    CLASS = "class"
    METHOD = "method"
    FUNCTION = "function"
    PROPERTY = "property"
    VARIABLE = "variable"
    IMPORT = "import"
    COMMENT = "comment"
    DECORATOR = "decorator"


class CodeSource(Enum):
    """Source of code elements."""
    GENERATED = "generated"    # Generated by PgForge
    CUSTOM = "custom"         # Added by developers
    MODIFIED = "modified"     # Generated but modified by developers
    UNKNOWN = "unknown"       # Cannot determine source


class MergeStrategy(Enum):
    """Strategies for merging code."""
    PRESERVE_CUSTOM = "preserve_custom"      # Favor custom code
    UPDATE_GENERATED = "update_generated"   # Favor generated code
    MERGE_INTELLIGENT = "merge_intelligent" # Intelligent merging
    ASK_USER = "ask_user"                   # Require user decision


class ConflictResolution(Enum):
    """Conflict resolution strategies."""
    AUTO_RESOLVE = "auto_resolve"    # Automatic resolution
    MANUAL_REVIEW = "manual_review"  # Require manual review
    BACKUP_BOTH = "backup_both"      # Keep both versions
    SKIP_CONFLICT = "skip_conflict"  # Skip conflicting files


@dataclass
class CodeElement:
    """Represents a code element with metadata."""
    name: str
    element_type: CodeElementType
    source: CodeSource
    content: str
    line_start: int
    line_end: int
    ast_node: Optional[ast.AST] = None
    dependencies: List[str] = field(default_factory=list)
    annotations: Dict[str, Any] = field(default_factory=dict)
    hash_signature: Optional[str] = None
    
    def __post_init__(self):
        """Calculate hash signature for change detection."""
        if not self.hash_signature:
            content_normalized = re.sub(r'\s+', ' ', self.content.strip())
            self.hash_signature = hashlib.md5(content_normalized.encode()).hexdigest()


@dataclass
class CodeFile:
    """Represents a code file with analyzed elements."""
    file_path: str
    original_content: str
    generated_content: Optional[str] = None
    elements: List[CodeElement] = field(default_factory=list)
    imports: List[str] = field(default_factory=list)
    custom_elements: List[CodeElement] = field(default_factory=list)
    generated_elements: List[CodeElement] = field(default_factory=list)
    modified_elements: List[CodeElement] = field(default_factory=list)
    file_hash: Optional[str] = None
    last_modified: Optional[datetime] = None
    
    def __post_init__(self):
        """Calculate file hash and categorize elements."""
        if not self.file_hash:
            self.file_hash = hashlib.md5(self.original_content.encode()).hexdigest()
        
        # Categorize elements by source
        for element in self.elements:
            if element.source == CodeSource.CUSTOM:
                self.custom_elements.append(element)
            elif element.source == CodeSource.GENERATED:
                self.generated_elements.append(element)
            elif element.source == CodeSource.MODIFIED:
                self.modified_elements.append(element)


@dataclass
class MergeConflict:
    """Represents a merge conflict between custom and generated code."""
    file_path: str
    element_name: str
    conflict_type: str
    custom_content: str
    generated_content: str
    suggested_resolution: str
    auto_resolvable: bool
    severity: str = "medium"


@dataclass
class RegenerationResult:
    """Result of code regeneration process."""
    success: bool
    files_processed: int
    files_updated: int
    conflicts_found: int
    conflicts_resolved: int
    backup_path: Optional[str] = None
    conflicts: List[MergeConflict] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    performance_stats: Dict[str, float] = field(default_factory=dict)


class SmartCodeRegenerator:
    """
    Smart Code Regeneration Engine with Custom Code Preservation
    
    Features:
    - AST-based code analysis for precise element detection
    - Intelligent source detection (generated vs custom vs modified)
    - Advanced merging strategies with conflict resolution
    - Safe backup and rollback mechanisms
    - Performance optimization for large codebases
    - Detailed reporting and conflict visualization
    """
    
    def __init__(self, base_directory: str, backup_directory: Optional[str] = None):
        """
        Initialize the smart code regenerator.
        
        Args:
            base_directory: Base directory containing code to regenerate
            backup_directory: Directory for storing backups
        """
        self.base_directory = Path(base_directory)
        self.backup_directory = Path(backup_directory) if backup_directory else self.base_directory / '.backups'
        
        # Ensure directories exist
        self.backup_directory.mkdir(parents=True, exist_ok=True)
        
        # Configuration
        self.merge_strategy = MergeStrategy.MERGE_INTELLIGENT
        self.conflict_resolution = ConflictResolution.AUTO_RESOLVE
        
        # Code analysis patterns
        self.generated_patterns = self._initialize_generated_patterns()
        self.custom_indicators = self._initialize_custom_indicators()
        
        # Performance tracking
        self.performance_stats = {
            'files_analyzed': 0,
            'analysis_time': 0.0,
            'merge_time': 0.0,
            'backup_time': 0.0
        }
        
        logger.info(f"SmartCodeRegenerator initialized for {self.base_directory}")
    
    def regenerate_code(self, file_patterns: List[str], 
                       new_generated_content: Dict[str, str],
                       **options) -> RegenerationResult:
        """
        Regenerate code with intelligent custom code preservation.
        
        Args:
            file_patterns: Patterns of files to regenerate
            new_generated_content: Dictionary of file_path -> new generated content
            **options: Additional regeneration options
            
        Returns:
            RegenerationResult with detailed information about the process
        """
        start_time = time.time()
        
        logger.info(f"Starting smart code regeneration for {len(file_patterns)} patterns")
        
        try:
            # Create backup
            backup_path = self._create_backup()
            
            # Find and analyze existing files
            existing_files = self._find_files(file_patterns)
            analyzed_files = self._analyze_files(existing_files)
            
            # Perform intelligent merging
            merge_results = self._merge_code(analyzed_files, new_generated_content, **options)
            
            # Calculate performance stats
            total_time = time.time() - start_time
            self.performance_stats.update({
                'total_regeneration_time': total_time,
                'files_processed': len(analyzed_files),
                'average_time_per_file': total_time / max(1, len(analyzed_files))
            })
            
            result = RegenerationResult(
                success=len(merge_results.errors) == 0,
                files_processed=len(analyzed_files),
                files_updated=merge_results.files_updated,
                conflicts_found=len(merge_results.conflicts),
                conflicts_resolved=merge_results.conflicts_resolved,
                backup_path=str(backup_path),
                conflicts=merge_results.conflicts,
                errors=merge_results.errors,
                warnings=merge_results.warnings,
                performance_stats=self.performance_stats
            )
            
            # Log results
            self._log_regeneration_results(result)
            
            return result
            
        except Exception as e:
            logger.error(f"Code regeneration failed: {str(e)}")
            return RegenerationResult(
                success=False,
                files_processed=0,
                files_updated=0,
                conflicts_found=0,
                conflicts_resolved=0,
                errors=[str(e)],
                performance_stats=self.performance_stats
            )
    
    def _create_backup(self) -> Path:
        """Create a backup of current code state."""
        backup_start = time.time()
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = self.backup_directory / f"backup_{timestamp}"
        
        # Copy entire directory structure
        shutil.copytree(self.base_directory, backup_path, 
                       ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '.git'))
        
        backup_time = time.time() - backup_start
        self.performance_stats['backup_time'] = backup_time
        
        logger.info(f"Created backup at {backup_path} in {backup_time:.2f}s")
        return backup_path
    
    def _find_files(self, patterns: List[str]) -> List[Path]:
        """Find files matching the given patterns."""
        found_files = []
        
        for pattern in patterns:
            # Support glob patterns
            if '*' in pattern or '?' in pattern:
                found_files.extend(self.base_directory.glob(pattern))
            else:
                file_path = self.base_directory / pattern
                if file_path.exists():
                    found_files.append(file_path)
        
        # Filter for Python files only
        python_files = [f for f in found_files if f.suffix == '.py']
        
        logger.info(f"Found {len(python_files)} Python files to analyze")
        return python_files
    
    def _analyze_files(self, file_paths: List[Path]) -> List[CodeFile]:
        """Analyze existing files to identify custom vs generated code."""
        analysis_start = time.time()
        
        analyzed_files = []
        
        for file_path in file_paths:
            try:
                analyzed_file = self._analyze_file(file_path)
                analyzed_files.append(analyzed_file)
                
            except Exception as e:
                logger.error(f"Failed to analyze {file_path}: {str(e)}")
        
        analysis_time = time.time() - analysis_start
        self.performance_stats.update({
            'analysis_time': analysis_time,
            'files_analyzed': len(analyzed_files)
        })
        
        logger.info(f"Analyzed {len(analyzed_files)} files in {analysis_time:.2f}s")
        return analyzed_files
    
    def _analyze_file(self, file_path: Path) -> CodeFile:
        """Analyze a single file to identify code elements and their sources."""
        
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Parse AST
        try:
            tree = ast.parse(content)
        except SyntaxError as e:
            logger.warning(f"Syntax error in {file_path}: {str(e)}")
            # Return basic file info without detailed analysis
            return CodeFile(
                file_path=str(file_path),
                original_content=content,
                last_modified=datetime.fromtimestamp(file_path.stat().st_mtime)
            )
        
        # Extract elements
        elements = []
        imports = []
        
        # Analyze top-level elements
        for node in ast.walk(tree):
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                element = self._analyze_code_element(node, content, file_path)
                elements.append(element)
            
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                import_statement = self._extract_import_statement(node, content)
                imports.append(import_statement)
        
        return CodeFile(
            file_path=str(file_path),
            original_content=content,
            elements=elements,
            imports=imports,
            last_modified=datetime.fromtimestamp(file_path.stat().st_mtime)
        )
    
    def _analyze_code_element(self, node: ast.AST, content: str, file_path: Path) -> CodeElement:
        """Analyze a single code element to determine its source and characteristics."""
        
        # Extract element content
        lines = content.split('\n')
        
        if hasattr(node, 'lineno') and hasattr(node, 'end_lineno'):
            start_line = node.lineno - 1  # Convert to 0-based indexing
            end_line = node.end_lineno if node.end_lineno else start_line + 1
            element_content = '\n'.join(lines[start_line:end_line])
        else:
            # Fallback for nodes without line number info
            element_content = ast.unparse(node) if hasattr(ast, 'unparse') else str(node)
            start_line = 0
            end_line = 0
        
        # Determine element type
        if isinstance(node, ast.ClassDef):
            element_type = CodeElementType.CLASS
            element_name = node.name
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            element_type = CodeElementType.METHOD if self._is_method(node, content) else CodeElementType.FUNCTION
            element_name = node.name
        else:
            element_type = CodeElementType.VARIABLE
            element_name = getattr(node, 'id', 'unknown')
        
        # Determine source (generated vs custom)
        source = self._determine_code_source(element_content, element_name, file_path)
        
        # Extract dependencies
        dependencies = self._extract_dependencies(node)
        
        # Extract annotations
        annotations = self._extract_annotations(node, element_content)
        
        return CodeElement(
            name=element_name,
            element_type=element_type,
            source=source,
            content=element_content,
            line_start=start_line,
            line_end=end_line,
            ast_node=node,
            dependencies=dependencies,
            annotations=annotations
        )
    
    def _determine_code_source(self, content: str, element_name: str, file_path: Path) -> CodeSource:
        """Determine if code element is generated, custom, or modified."""
        
        # Check for generated code patterns
        for pattern in self.generated_patterns:
            if re.search(pattern, content, re.IGNORECASE | re.MULTILINE):
                # Check if it has been modified
                if self._has_custom_modifications(content):
                    return CodeSource.MODIFIED
                else:
                    return CodeSource.GENERATED
        
        # Check for custom code indicators
        for indicator in self.custom_indicators:
            if indicator in content.lower():
                return CodeSource.CUSTOM
        
        # Advanced heuristics based on code complexity and patterns
        if self._appears_generated(content):
            return CodeSource.GENERATED
        elif self._appears_custom(content):
            return CodeSource.CUSTOM
        
        return CodeSource.UNKNOWN
    
    def _has_custom_modifications(self, content: str) -> bool:
        """Check if generated code has custom modifications."""
        
        # Look for custom comments
        custom_comment_patterns = [
            r'#\s*custom',
            r'#\s*added by',
            r'#\s*modified',
            r'#\s*todo',
            r'#\s*fixme',
            r'#\s*note'
        ]
        
        for pattern in custom_comment_patterns:
            if re.search(pattern, content, re.IGNORECASE):
                return True
        
        # Look for custom docstrings
        if '"""' in content and any(word in content.lower() for word in ['custom', 'modified', 'added']):
            return True
        
        # Look for complex business logic (heuristic)
        complexity_indicators = [
            'if.*and.*or',  # Complex conditionals
            'try:.*except.*finally',  # Error handling
            'with.*as',  # Context managers
            'yield',  # Generators
            'lambda',  # Lambda functions
        ]
        
        complex_patterns_found = sum(1 for pattern in complexity_indicators 
                                   if re.search(pattern, content, re.IGNORECASE))
        
        return complex_patterns_found >= 2  # Threshold for complexity
    
    def _appears_generated(self, content: str) -> bool:
        """Heuristic to determine if content appears to be generated."""
        
        # Generated code typically has:
        # - Repetitive patterns
        # - Minimal comments
        # - Standard naming conventions
        # - Boilerplate structure
        
        indicators = 0
        
        # Check for boilerplate patterns
        boilerplate_patterns = [
            r'def\s+__init__\(self.*\):',
            r'def\s+__str__\(self\):',
            r'def\s+__repr__\(self\):',
            r'class\s+\w+\(.*ModelView.*\):',
            r'datamodel\s*=\s*SQLAInterface',
        ]
        
        for pattern in boilerplate_patterns:
            if re.search(pattern, content):
                indicators += 1
        
        # Check comment density (generated code typically has fewer comments)
        lines = content.split('\n')
        comment_lines = [line for line in lines if line.strip().startswith('#')]
        comment_ratio = len(comment_lines) / max(1, len(lines))
        
        if comment_ratio < 0.1:  # Less than 10% comments suggests generated code
            indicators += 1
        
        return indicators >= 2
    
    def _appears_custom(self, content: str) -> bool:
        """Heuristic to determine if content appears to be custom."""
        
        # Custom code typically has:
        # - Meaningful comments
        # - Business logic
        # - Error handling
        # - Complex control flow
        
        indicators = 0
        
        # Check for meaningful comments
        meaningful_comment_patterns = [
            r'#.*business',
            r'#.*logic',
            r'#.*important',
            r'#.*note',
            r'#.*todo',
        ]
        
        for pattern in meaningful_comment_patterns:
            if re.search(pattern, content, re.IGNORECASE):
                indicators += 1
        
        # Check for complex control structures
        complex_structures = [
            r'if\s+.*:\s*#.*',  # Commented conditionals
            r'try:.*except.*:.*#',  # Commented error handling
            r'for\s+.*:\s*#.*',  # Commented loops
            r'while\s+.*:\s*#.*',  # Commented while loops
        ]
        
        for pattern in complex_structures:
            if re.search(pattern, content, re.IGNORECASE | re.MULTILINE | re.DOTALL):
                indicators += 1
        
        return indicators >= 2
    
    def _is_method(self, node: ast.FunctionDef, content: str) -> bool:
        """Determine if a function is actually a method (inside a class)."""
        
        # Simple heuristic: check if first parameter is 'self' or 'cls'
        if node.args.args and len(node.args.args) > 0:
            first_arg = node.args.args[0].arg
            return first_arg in ('self', 'cls')
        
        return False
    
    def _extract_dependencies(self, node: ast.AST) -> List[str]:
        """Extract dependencies for a code element."""
        
        dependencies = []
        
        # Extract function/method calls
        for child in ast.walk(node):
            if isinstance(child, ast.Call):
                if isinstance(child.func, ast.Name):
                    dependencies.append(child.func.id)
                elif isinstance(child.func, ast.Attribute):
                    # Handle method calls like obj.method()
                    if isinstance(child.func.value, ast.Name):
                        dependencies.append(f"{child.func.value.id}.{child.func.attr}")
        
        return list(set(dependencies))  # Remove duplicates
    
    def _extract_annotations(self, node: ast.AST, content: str) -> Dict[str, Any]:
        """Extract annotations and metadata from code element."""
        
        annotations = {}
        
        # Extract docstring
        if isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.AsyncFunctionDef)):
            docstring = ast.get_docstring(node)
            if docstring:
                annotations['docstring'] = docstring
        
        # Extract decorators
        if hasattr(node, 'decorator_list') and node.decorator_list:
            decorators = []
            for decorator in node.decorator_list:
                if isinstance(decorator, ast.Name):
                    decorators.append(decorator.id)
                elif isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name):
                    decorators.append(decorator.func.id)
            annotations['decorators'] = decorators
        
        # Extract type hints
        if hasattr(node, 'returns') and node.returns:
            annotations['return_type'] = ast.unparse(node.returns) if hasattr(ast, 'unparse') else str(node.returns)
        
        return annotations
    
    def _extract_import_statement(self, node: ast.AST, content: str) -> str:
        """Extract import statement as string."""
        
        if isinstance(node, ast.Import):
            return f"import {', '.join(alias.name for alias in node.names)}"
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ''
            names = ', '.join(alias.name for alias in node.names)
            return f"from {module} import {names}"
        
        return ""
    
    def _merge_code(self, analyzed_files: List[CodeFile], 
                   new_generated_content: Dict[str, str],
                   **options) -> RegenerationResult:
        """Merge custom code with new generated content."""
        
        merge_start = time.time()
        
        conflicts = []
        errors = []
        warnings = []
        files_updated = 0
        conflicts_resolved = 0
        
        for analyzed_file in analyzed_files:
            try:
                # Get new generated content for this file
                relative_path = str(Path(analyzed_file.file_path).relative_to(self.base_directory))
                new_content = new_generated_content.get(relative_path)
                
                if not new_content:
                    logger.debug(f"No new content for {analyzed_file.file_path}, skipping")
                    continue
                
                # Perform intelligent merge
                merge_result = self._merge_single_file(analyzed_file, new_content, **options)
                
                if merge_result['conflicts']:
                    conflicts.extend(merge_result['conflicts'])
                
                if merge_result['errors']:
                    errors.extend(merge_result['errors'])
                
                if merge_result['warnings']:
                    warnings.extend(merge_result['warnings'])
                
                if merge_result['updated']:
                    files_updated += 1
                
                conflicts_resolved += merge_result['conflicts_resolved']
                
            except Exception as e:
                error_msg = f"Failed to merge {analyzed_file.file_path}: {str(e)}"
                errors.append(error_msg)
                logger.error(error_msg)
        
        merge_time = time.time() - merge_start
        self.performance_stats['merge_time'] = merge_time
        
        return RegenerationResult(
            success=len(errors) == 0,
            files_processed=len(analyzed_files),
            files_updated=files_updated,
            conflicts_found=len(conflicts),
            conflicts_resolved=conflicts_resolved,
            conflicts=conflicts,
            errors=errors,
            warnings=warnings
        )
    
    def _merge_single_file(self, analyzed_file: CodeFile, new_content: str, 
                          **options) -> Dict[str, Any]:
        """Merge custom code with new generated content for a single file."""
        
        # Parse new generated content
        try:
            new_ast = ast.parse(new_content)
        except SyntaxError as e:
            return {
                'updated': False,
                'conflicts': [],
                'errors': [f"Syntax error in new content: {str(e)}"],
                'warnings': [],
                'conflicts_resolved': 0
            }
        
        # Extract elements from new content
        new_elements = self._extract_elements_from_ast(new_ast, new_content)
        
        # Identify conflicts between existing custom code and new generated code
        conflicts = self._identify_conflicts(analyzed_file, new_elements)
        
        # Resolve conflicts using selected strategy
        resolved_conflicts, unresolved_conflicts = self._resolve_conflicts(conflicts)
        
        # Generate merged content
        merged_content = self._generate_merged_content(analyzed_file, new_elements, resolved_conflicts)
        
        # Write merged content back to file
        updated = False
        if merged_content and merged_content != analyzed_file.original_content:
            try:
                with open(analyzed_file.file_path, 'w', encoding='utf-8') as f:
                    f.write(merged_content)
                updated = True
                logger.info(f"Updated {analyzed_file.file_path}")
            except Exception as e:
                return {
                    'updated': False,
                    'conflicts': unresolved_conflicts,
                    'errors': [f"Failed to write file: {str(e)}"],
                    'warnings': [],
                    'conflicts_resolved': len(resolved_conflicts)
                }
        
        return {
            'updated': updated,
            'conflicts': unresolved_conflicts,
            'errors': [],
            'warnings': [],
            'conflicts_resolved': len(resolved_conflicts)
        }
    
    def _extract_elements_from_ast(self, ast_tree: ast.AST, content: str) -> List[CodeElement]:
        """Extract code elements from AST tree."""
        
        elements = []
        lines = content.split('\n')
        
        for node in ast.walk(ast_tree):
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                
                # Extract content
                if hasattr(node, 'lineno') and hasattr(node, 'end_lineno'):
                    start_line = node.lineno - 1
                    end_line = node.end_lineno if node.end_lineno else start_line + 1
                    element_content = '\n'.join(lines[start_line:end_line])
                else:
                    element_content = ast.unparse(node) if hasattr(ast, 'unparse') else str(node)
                    start_line = 0
                    end_line = 0
                
                # Create element (assume generated since it's new content)
                element = CodeElement(
                    name=node.name,
                    element_type=CodeElementType.CLASS if isinstance(node, ast.ClassDef) else CodeElementType.METHOD,
                    source=CodeSource.GENERATED,
                    content=element_content,
                    line_start=start_line,
                    line_end=end_line,
                    ast_node=node
                )
                
                elements.append(element)
        
        return elements
    
    def _identify_conflicts(self, analyzed_file: CodeFile, 
                           new_elements: List[CodeElement]) -> List[MergeConflict]:
        """Identify conflicts between existing and new code elements."""
        
        conflicts = []
        
        # Create maps for easy lookup
        existing_elements = {elem.name: elem for elem in analyzed_file.elements}
        new_elements_map = {elem.name: elem for elem in new_elements}
        
        # Check for conflicts
        for name, new_element in new_elements_map.items():
            existing_element = existing_elements.get(name)
            
            if existing_element:
                # Element exists in both - check for conflicts
                if existing_element.source in (CodeSource.CUSTOM, CodeSource.MODIFIED):
                    # Custom or modified code conflicts with new generated code
                    conflict = MergeConflict(
                        file_path=analyzed_file.file_path,
                        element_name=name,
                        conflict_type=f"{existing_element.source.value}_vs_generated",
                        custom_content=existing_element.content,
                        generated_content=new_element.content,
                        suggested_resolution=self._suggest_resolution(existing_element, new_element),
                        auto_resolvable=self._is_auto_resolvable(existing_element, new_element)
                    )
                    conflicts.append(conflict)
        
        return conflicts
    
    def _suggest_resolution(self, existing_element: CodeElement, 
                           new_element: CodeElement) -> str:
        """Suggest resolution strategy for merge conflict."""
        
        if existing_element.source == CodeSource.CUSTOM:
            return "preserve_custom"  # Always preserve completely custom code
        
        elif existing_element.source == CodeSource.MODIFIED:
            # For modified code, suggest intelligent merge
            if self._has_minor_modifications(existing_element):
                return "merge_with_modifications"
            else:
                return "review_required"
        
        else:
            return "use_generated"  # Default to new generated code
    
    def _is_auto_resolvable(self, existing_element: CodeElement, 
                           new_element: CodeElement) -> bool:
        """Determine if conflict can be automatically resolved."""
        
        # Can auto-resolve if:
        # 1. Only minor formatting differences
        # 2. Only docstring differences
        # 3. Only import additions
        
        if existing_element.source == CodeSource.CUSTOM:
            return False  # Never auto-resolve custom code
        
        # Check for minor differences
        existing_normalized = self._normalize_code(existing_element.content)
        new_normalized = self._normalize_code(new_element.content)
        
        # Calculate similarity
        similarity = difflib.SequenceMatcher(None, existing_normalized, new_normalized).ratio()
        
        return similarity > 0.8  # 80% similarity threshold for auto-resolution
    
    def _has_minor_modifications(self, element: CodeElement) -> bool:
        """Check if element has only minor modifications."""
        
        # Minor modifications include:
        # - Added comments
        # - Changed variable names
        # - Added logging statements
        # - Small refactoring
        
        minor_indicators = [
            r'#.*',  # Comments
            r'logger\.',  # Logging
            r'print\(',  # Debug prints
            r'TODO',  # TODO comments
            r'FIXME',  # FIXME comments
        ]
        
        for pattern in minor_indicators:
            if re.search(pattern, element.content):
                return True
        
        return False
    
    def _normalize_code(self, code: str) -> str:
        """Normalize code for comparison (remove whitespace, comments, etc.)."""
        
        # Remove comments
        code = re.sub(r'#.*$', '', code, flags=re.MULTILINE)
        
        # Remove extra whitespace
        code = re.sub(r'\s+', ' ', code)
        
        # Remove empty lines
        code = re.sub(r'\n\s*\n', '\n', code)
        
        return code.strip()
    
    def _resolve_conflicts(self, conflicts: List[MergeConflict]) -> Tuple[List[MergeConflict], List[MergeConflict]]:
        """Resolve conflicts based on configured strategy."""
        
        resolved = []
        unresolved = []
        
        for conflict in conflicts:
            if conflict.auto_resolvable and self.conflict_resolution == ConflictResolution.AUTO_RESOLVE:
                resolved.append(conflict)
            else:
                unresolved.append(conflict)
        
        return resolved, unresolved
    
    def _generate_merged_content(self, analyzed_file: CodeFile, 
                                new_elements: List[CodeElement],
                                resolved_conflicts: List[MergeConflict]) -> str:
        """Generate merged content combining custom and generated code."""
        
        # Start with new generated content as base
        merged_lines = analyzed_file.generated_content.split('\n') if analyzed_file.generated_content else []
        
        # If no generated content, start with original
        if not merged_lines:
            merged_lines = analyzed_file.original_content.split('\n')
        
        # Apply custom elements that don't conflict
        custom_elements = [elem for elem in analyzed_file.custom_elements 
                          if not any(conflict.element_name == elem.name for conflict in resolved_conflicts)]
        
        # Insert custom elements at appropriate positions
        for custom_element in custom_elements:
            # Find insertion point (end of file for now, could be more sophisticated)
            merged_lines.append('')  # Add blank line
            merged_lines.extend(custom_element.content.split('\n'))
        
        return '\n'.join(merged_lines)
    
    def _log_regeneration_results(self, result: RegenerationResult):
        """Log detailed results of regeneration process."""
        
        if result.success:
            logger.info(f"✅ Code regeneration completed successfully")
        else:
            logger.error(f"❌ Code regeneration completed with errors")
        
        logger.info(f"📊 Results Summary:")
        logger.info(f"   Files processed: {result.files_processed}")
        logger.info(f"   Files updated: {result.files_updated}")
        logger.info(f"   Conflicts found: {result.conflicts_found}")
        logger.info(f"   Conflicts resolved: {result.conflicts_resolved}")
        
        if result.errors:
            logger.error(f"   Errors: {len(result.errors)}")
            for error in result.errors[:3]:  # Show first 3 errors
                logger.error(f"     - {error}")
        
        if result.warnings:
            logger.warning(f"   Warnings: {len(result.warnings)}")
            for warning in result.warnings[:3]:  # Show first 3 warnings
                logger.warning(f"     - {warning}")
        
        # Performance stats
        stats = result.performance_stats
        if stats:
            logger.info(f"⚡ Performance Stats:")
            logger.info(f"   Total time: {stats.get('total_regeneration_time', 0):.2f}s")
            logger.info(f"   Average per file: {stats.get('average_time_per_file', 0):.3f}s")
            logger.info(f"   Analysis time: {stats.get('analysis_time', 0):.2f}s")
            logger.info(f"   Merge time: {stats.get('merge_time', 0):.2f}s")
    
    def _initialize_generated_patterns(self) -> List[str]:
        """Initialize patterns that identify generated code."""
        
        return [
            r'"""[\s\S]*?Generated by PgForge[\s\S]*?"""',
            r'#.*Generated automatically',
            r'#.*Do not modify this file',
            r'#.*Auto-generated',
            r'class\s+\w+View\(ModelView\):',
            r'datamodel\s*=\s*SQLAInterface',
            r'#.*PgForge Generator',
        ]
    
    def _initialize_custom_indicators(self) -> List[str]:
        """Initialize indicators of custom code."""
        
        return [
            '# custom',
            '# added by',
            '# modified',
            '# business logic',
            '# important',
            'todo',
            'fixme',
            'hack',
            'workaround',
        ]


# Convenience functions for easy usage
def regenerate_with_preservation(base_directory: str, 
                                file_patterns: List[str],
                                new_generated_content: Dict[str, str],
                                **options) -> RegenerationResult:
    """
    Convenience function for smart code regeneration.
    
    Args:
        base_directory: Directory containing code to regenerate
        file_patterns: Patterns of files to process
        new_generated_content: New generated content by file path
        **options: Additional options
        
    Returns:
        RegenerationResult with detailed process information
    """
    regenerator = SmartCodeRegenerator(base_directory)
    return regenerator.regenerate_code(file_patterns, new_generated_content, **options)


def create_conflict_report(result: RegenerationResult, output_path: str = "conflict_report.html"):
    """
    Create an HTML report of merge conflicts for manual review.
    
    Args:
        result: Regeneration result with conflicts
        output_path: Path to save the HTML report
    """
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Code Regeneration Conflict Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            .conflict {{ border: 1px solid #ccc; margin: 20px 0; padding: 20px; }}
            .custom-code {{ background-color: #e8f5e8; padding: 10px; }}
            .generated-code {{ background-color: #f5e8e8; padding: 10px; }}
            .resolution {{ background-color: #e8e8f5; padding: 10px; }}
            pre {{ white-space: pre-wrap; }}
        </style>
    </head>
    <body>
        <h1>Code Regeneration Conflict Report</h1>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        <h2>Summary</h2>
        <ul>
            <li>Files processed: {result.files_processed}</li>
            <li>Files updated: {result.files_updated}</li>
            <li>Conflicts found: {result.conflicts_found}</li>
            <li>Conflicts resolved: {result.conflicts_resolved}</li>
        </ul>
        
        <h2>Conflicts Requiring Manual Review</h2>
    """
    
    for i, conflict in enumerate(result.conflicts, 1):
        html_content += f"""
        <div class="conflict">
            <h3>Conflict {i}: {conflict.element_name} in {conflict.file_path}</h3>
            <p><strong>Type:</strong> {conflict.conflict_type}</p>
            <p><strong>Suggested Resolution:</strong> {conflict.suggested_resolution}</p>
            
            <h4>Custom Code:</h4>
            <div class="custom-code">
                <pre>{conflict.custom_content}</pre>
            </div>
            
            <h4>Generated Code:</h4>
            <div class="generated-code">
                <pre>{conflict.generated_content}</pre>
            </div>
            
            <div class="resolution">
                <strong>Recommended Action:</strong> {conflict.suggested_resolution}
            </div>
        </div>
        """
    
    html_content += """
    </body>
    </html>
    """
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    logger.info(f"Conflict report saved to {output_path}")